package orchestrator

import (
	"context"
	"testing"

	"github.com/Nyukimin/picoclaw_multiLLM/internal/domain/capability"
	"github.com/Nyukimin/picoclaw_multiLLM/internal/domain/patch"
	"github.com/Nyukimin/picoclaw_multiLLM/internal/domain/proposal"
	"github.com/Nyukimin/picoclaw_multiLLM/internal/domain/routing"
	"github.com/Nyukimin/picoclaw_multiLLM/internal/domain/task"
)

// TestCodeExecutor_CODE1Route はCODE1明示ルートのテスト（RED）
func TestCodeExecutor_CODE1Route(t *testing.T) {
	coder1 := &mockCoderAgent{response: "CODE1 response"}
	executor := NewDefaultCodeExecutor(coder1, nil, nil, nil, nil, nil, noopEventEmitter)

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE1,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}

	if resp.Response != "CODE1 response" {
		t.Errorf("Expected 'CODE1 response', got '%s'", resp.Response)
	}

	if resp.Handled {
		t.Error("CODE1 should not use Proposal path")
	}
}

// TestCodeExecutor_CODE3_WithProposal はCODE3 Proposal実行のテスト（RED）
func TestCodeExecutor_CODE3_WithProposal(t *testing.T) {
	testProposal := proposal.NewProposal(
		"Test plan",
		`[{"type": "file_edit", "action": "create", "target": "test.txt", "content": "test"}]`,
		"Low risk",
		"Low cost",
	)

	coder3 := &mockCoderAgentWithProposal{
		response: "Proposal generated",
		proposal: testProposal,
	}

	workerService := &recordingCodeWorkerExecutionService{}
	executor := NewDefaultCodeExecutor(nil, nil, coder3, nil, workerService, nil, noopEventEmitter)

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE3,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}

	if !resp.Handled {
		t.Error("CODE3 with Proposal should be handled via Proposal path")
	}

	// レスポンスにPlanが含まれることを確認
	if resp.Response == "" {
		t.Error("Expected non-empty response")
	}
	if workerService.calls != 1 {
		t.Fatalf("worker ExecuteProposal calls=%d, want 1", workerService.calls)
	}
	if workerService.jobID.String() != jobID.String() {
		t.Fatalf("worker jobID=%s, want %s", workerService.jobID.String(), jobID.String())
	}
	if workerService.proposal != testProposal {
		t.Fatal("worker should receive the same proposal instance generated by coder")
	}
}

func TestCodeExecutor_CODE2_WithProposal_ExecutesPatch(t *testing.T) {
	testProposal := proposal.NewProposal(
		"Implement requested change",
		`[{"type": "file_edit", "action": "create", "target": "implemented.txt", "content": "done"}]`,
		"Low risk",
		"Low cost",
	)

	coder2 := &mockCoderAgentWithProposal{
		response: "plain response should not be used",
		proposal: testProposal,
	}

	workerService := &recordingCodeWorkerExecutionService{}
	executor := NewDefaultCodeExecutor(nil, coder2, nil, nil, workerService, nil, noopEventEmitter)

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "README.md を更新して", "test", "chat-1"),
		Route:     routing.RouteCODE2,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}
	if !resp.Handled {
		t.Fatal("CODE2 with Proposal should be handled via Proposal path")
	}
	if resp.Response == "" {
		t.Fatal("Expected non-empty response")
	}
	if workerService.calls != 1 {
		t.Fatalf("worker ExecuteProposal calls=%d, want 1", workerService.calls)
	}
}

func TestCodeExecutor_CODEDynamicSelectsCODE3_UsesProposalPath(t *testing.T) {
	testProposal := proposal.NewProposal(
		"Test plan",
		`[{"type": "file_edit", "action": "create", "target": "dynamic-code3.txt", "content": "ok"}]`,
		"Low risk",
		"Low cost",
	)

	coder3 := &mockCoderAgentWithProposal{
		response: "plain response should not be used",
		proposal: testProposal,
	}

	workerService := &recordingCodeWorkerExecutionService{}
	executor := NewDefaultCodeExecutor(nil, nil, coder3, nil, workerService, nil, noopEventEmitter).WithCapabilities([]capability.CoderCapability{
		{Name: "coder3", Quality: 5, Available: true},
	})

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}
	if !resp.Handled {
		t.Fatal("CODE dynamically selected as CODE3 quality should use Proposal path")
	}
	if resp.Response == "" {
		t.Fatal("Expected non-empty response")
	}
	if workerService.calls != 1 {
		t.Fatalf("worker ExecuteProposal calls=%d, want 1", workerService.calls)
	}
}

// TestCodeExecutor_CODE_GenericRoute_Fallback はCODE汎用ルートのフォールバックテスト
func TestCodeExecutor_CODE_GenericRoute_Fallback(t *testing.T) {
	// coder1がnilの場合にcoder2にフォールバック
	coder2 := &mockCoderAgent{response: "CODE2 fallback response"}

	executor := NewDefaultCodeExecutor(nil, coder2, nil, nil, nil, nil, noopEventEmitter)

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}

	// coder1がnilならcoder2にフォールバック
	if resp.Response != "CODE2 fallback response" {
		t.Errorf("Expected fallback to coder2, got '%s'", resp.Response)
	}
}

// ヘルパー関数
func noopEventEmitter(eventType, from, to, content, route, jobID, sessionID, channel, chatID string) {
	// テスト用の空実装
}

type recordingCodeWorkerExecutionService struct {
	calls    int
	jobID    task.JobID
	proposal *proposal.Proposal
}

func (s *recordingCodeWorkerExecutionService) ExecuteProposal(ctx context.Context, jobID task.JobID, p *proposal.Proposal) (*patch.PatchExecutionResult, error) {
	s.calls++
	s.jobID = jobID
	s.proposal = p
	result := patch.NewPatchExecutionResult()
	result.AddResult(patch.CommandResult{Success: true, Output: "ok"})
	return result.WithSummary("実行: 1 件, 成功: 1 件, 失敗: 0 件"), nil
}
