package orchestrator

import (
	"context"
	"errors"
	"strings"
	"testing"

	"github.com/Nyukimin/picoclaw_multiLLM/internal/domain/capability"
	"github.com/Nyukimin/picoclaw_multiLLM/internal/domain/patch"
	"github.com/Nyukimin/picoclaw_multiLLM/internal/domain/proposal"
	"github.com/Nyukimin/picoclaw_multiLLM/internal/domain/routing"
	domainskill "github.com/Nyukimin/picoclaw_multiLLM/internal/domain/skillgovernance"
	"github.com/Nyukimin/picoclaw_multiLLM/internal/domain/task"
)

// TestCodeExecutor_CODE1Route はCODE1明示ルートのテスト（RED）
func TestCodeExecutor_CODE1Route(t *testing.T) {
	coder1 := &mockCoderAgent{response: "CODE1 response"}
	executor := NewDefaultCodeExecutor(coder1, nil, nil, nil, nil, nil, noopEventEmitter)

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE1,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}

	if resp.Response != "CODE1 response" {
		t.Errorf("Expected 'CODE1 response', got '%s'", resp.Response)
	}

	if resp.Handled {
		t.Error("CODE1 should not use Proposal path")
	}
}

// TestCodeExecutor_CODE3_WithProposal はCODE3 Proposal実行のテスト（RED）
func TestCodeExecutor_CODE3_WithProposal(t *testing.T) {
	testProposal := proposal.NewProposal(
		"Test plan",
		`[{"type": "file_edit", "action": "create", "target": "test.txt", "content": "test"}]`,
		"Low risk",
		"Low cost",
	)

	coder3 := &mockCoderAgentWithProposal{
		response: "Proposal generated",
		proposal: testProposal,
	}

	workerService := &recordingCodeWorkerExecutionService{}
	executor := NewDefaultCodeExecutor(nil, nil, coder3, nil, workerService, nil, noopEventEmitter)

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE3,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}

	if !resp.Handled {
		t.Error("CODE3 with Proposal should be handled via Proposal path")
	}

	// レスポンスにPlanが含まれることを確認
	if resp.Response == "" {
		t.Error("Expected non-empty response")
	}
	if workerService.calls != 1 {
		t.Fatalf("worker ExecuteProposal calls=%d, want 1", workerService.calls)
	}
	if workerService.jobID.String() != jobID.String() {
		t.Fatalf("worker jobID=%s, want %s", workerService.jobID.String(), jobID.String())
	}
	if workerService.proposal != testProposal {
		t.Fatal("worker should receive the same proposal instance generated by coder")
	}
}

func TestCodeExecutor_CODE2_WithProposal_ExecutesPatch(t *testing.T) {
	testProposal := proposal.NewProposal(
		"Implement requested change",
		`[{"type": "file_edit", "action": "create", "target": "implemented.txt", "content": "done"}]`,
		"Low risk",
		"Low cost",
	)

	coder2 := &mockCoderAgentWithProposal{
		response: "plain response should not be used",
		proposal: testProposal,
	}

	workerService := &recordingCodeWorkerExecutionService{}
	executor := NewDefaultCodeExecutor(nil, coder2, nil, nil, workerService, nil, noopEventEmitter)

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "README.md を更新して", "test", "chat-1"),
		Route:     routing.RouteCODE2,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}
	if !resp.Handled {
		t.Fatal("CODE2 with Proposal should be handled via Proposal path")
	}
	if resp.Response == "" {
		t.Fatal("Expected non-empty response")
	}
	if workerService.calls != 1 {
		t.Fatalf("worker ExecuteProposal calls=%d, want 1", workerService.calls)
	}
}

func TestCodeExecutor_CODE3_WithProposalRecordsSkillChangeEvidence(t *testing.T) {
	testProposal := proposal.NewProposal(
		"Update Skill manifest",
		`diff --git a/skills/core/example/SKILL.md b/skills/core/example/SKILL.md`,
		"Low risk",
		"Low cost",
	)

	coder3 := &mockCoderAgentWithProposal{
		response: "plain response should not be used",
		proposal: testProposal,
	}
	workerService := &recordingCodeWorkerExecutionService{}
	evidence := &recordingCoderProposalEvidenceRecorder{}
	executor := NewDefaultCodeExecutor(nil, nil, coder3, nil, workerService, nil, noopEventEmitter).
		WithCoderProposalEvidenceRecorder(evidence)

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "Skillの挙動を変更して", "test", "chat-1"),
		Route:     routing.RouteCODE3,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	_, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("ExecuteCode failed: %v", err)
	}
	if len(evidence.items) != 1 {
		t.Fatalf("recorded evidence count=%d, want 1", len(evidence.items))
	}
	got := evidence.items[0]
	if got.JobID != jobID.String() || got.SessionID != "sess-1" || got.Route != "CODE3" || got.Agent != "coder3" {
		t.Fatalf("unexpected evidence metadata: %#v", got)
	}
	if got.Patch != testProposal.Patch() || got.Plan != testProposal.Plan() {
		t.Fatalf("proposal evidence did not preserve patch/plan: %#v", got)
	}
	if !got.Success || !strings.Contains(got.ExecutionSummary, "成功: 1 件") {
		t.Fatalf("expected successful execution evidence, got %#v", got)
	}
}

func TestCodeExecutor_CODEDynamicSelectsCODE3_UsesProposalPath(t *testing.T) {
	testProposal := proposal.NewProposal(
		"Test plan",
		`[{"type": "file_edit", "action": "create", "target": "dynamic-code3.txt", "content": "ok"}]`,
		"Low risk",
		"Low cost",
	)

	coder3 := &mockCoderAgentWithProposal{
		response: "plain response should not be used",
		proposal: testProposal,
	}

	workerService := &recordingCodeWorkerExecutionService{}
	executor := NewDefaultCodeExecutor(nil, nil, coder3, nil, workerService, nil, noopEventEmitter).WithCapabilities([]capability.CoderCapability{
		{Name: "coder3", Quality: 5, Available: true},
	})

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}
	if !resp.Handled {
		t.Fatal("CODE dynamically selected as CODE3 quality should use Proposal path")
	}
	if resp.Response == "" {
		t.Fatal("Expected non-empty response")
	}
	if workerService.calls != 1 {
		t.Fatalf("worker ExecuteProposal calls=%d, want 1", workerService.calls)
	}
}

func TestCodeExecutor_CODE_ReleasesCoderStatusAfterGenerateSuccess(t *testing.T) {
	status := NewCoderStatus()
	coder1 := &mockCoderAgent{response: "CODE response"}
	executor := NewDefaultCodeExecutor(coder1, nil, nil, nil, nil, status, noopEventEmitter)

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}
	if resp.Response != "CODE response" {
		t.Fatalf("Response=%q, want CODE response", resp.Response)
	}
	if status.IsBusy("coder1") {
		t.Fatal("coder1 should be released after successful Generate path")
	}
}

func TestCodeExecutor_CODE_ReleasesCoderStatusAfterGenerateError(t *testing.T) {
	status := NewCoderStatus()
	coderErr := errors.New("generate failed")
	coder1 := &failingCoderAgent{err: coderErr}
	executor := NewDefaultCodeExecutor(coder1, nil, nil, nil, nil, status, noopEventEmitter)

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	_, err := executor.ExecuteCode(context.Background(), req)
	if !errors.Is(err, coderErr) {
		t.Fatalf("Expected Generate error %v, got %v", coderErr, err)
	}
	if status.IsBusy("coder1") {
		t.Fatal("coder1 should be released after failed Generate path")
	}
}

func TestCodeExecutor_DegradedRouteNoticeDoesNotMeanProposalHandled(t *testing.T) {
	var events []codeExecutorEvent
	coder2 := &mockCoderAgent{response: "degraded generate response"}
	executor := NewDefaultCodeExecutor(nil, coder2, nil, nil, nil, nil, recordingCodeEventEmitter(&events)).WithCapabilities([]capability.CoderCapability{
		{Name: "coder2", Quality: 4, Available: true},
	})

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE3,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}
	if resp.Handled {
		t.Fatal("degraded route notice must not mark Generate path as proposal-handled")
	}
	if resp.Response != "degraded generate response" {
		t.Fatalf("Response=%q, want degraded generate response", resp.Response)
	}

	notice, ok := findCodeExecutorEvent(events, "agent.notice", "shiro", "mio")
	if !ok {
		t.Fatal("Expected degraded route notice event")
	}
	if notice.route != routing.RouteCODE3.String() {
		t.Fatalf("notice route=%q, want %q", notice.route, routing.RouteCODE3.String())
	}
	if !strings.Contains(notice.content, routing.RouteCODE3.String()) || !strings.Contains(notice.content, routing.RouteCODE2.String()) {
		t.Fatalf("notice content=%q should include requested and degraded routes", notice.content)
	}
}

func TestCodeExecutor_ProposalUnsupportedCoderFallsBackToGeneratePath(t *testing.T) {
	coder3 := &mockCoderAgent{response: "generate response"}
	workerService := &recordingCodeWorkerExecutionService{}
	executor := NewDefaultCodeExecutor(nil, nil, coder3, nil, workerService, nil, noopEventEmitter)

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE3,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}
	if resp.Handled {
		t.Fatal("coder without proposal support should stay on Generate path, not proposal-handled")
	}
	if resp.Response != "generate response" {
		t.Fatalf("Response=%q, want generate response", resp.Response)
	}
	if workerService.calls != 0 {
		t.Fatalf("worker ExecuteProposal calls=%d, want 0", workerService.calls)
	}
}

func TestCodeExecutor_WorkerExecutionErrorIsReturnedAsError(t *testing.T) {
	workerErr := errors.New("worker failed")
	testProposal := proposal.NewProposal(
		"Test plan",
		`[{"type": "shell", "command": "echo ok"}]`,
		"Low risk",
		"Low cost",
	)
	coder3 := &mockCoderAgentWithProposal{proposal: testProposal}
	workerService := &recordingCodeWorkerExecutionService{err: workerErr}
	var events []codeExecutorEvent
	executor := NewDefaultCodeExecutor(nil, nil, coder3, nil, workerService, nil, recordingCodeEventEmitter(&events))

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE3,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err == nil {
		t.Fatal("Expected worker execution error")
	}
	if !errors.Is(err, workerErr) {
		t.Fatalf("Expected wrapped worker error %v, got %v", workerErr, err)
	}
	if resp.Response != "" || resp.Handled {
		t.Fatalf("worker error should not produce handled success response: %#v", resp)
	}
	if workerService.calls != 1 {
		t.Fatalf("worker ExecuteProposal calls=%d, want 1", workerService.calls)
	}
	event, ok := findCodeExecutorEvent(events, "agent.response", "shiro", "mio")
	if !ok {
		t.Fatal("Expected worker error event from shiro to mio")
	}
	if !strings.Contains(event.content, "実行失敗") {
		t.Fatalf("worker error event content=%q, want execution failure", event.content)
	}
}

func TestCodeExecutor_GenerateErrorDoesNotEmitShiroSuccess(t *testing.T) {
	generateErr := errors.New("generate failed")
	coder1 := &failingCoderAgent{err: generateErr}
	var events []codeExecutorEvent
	executor := NewDefaultCodeExecutor(coder1, nil, nil, nil, nil, nil, recordingCodeEventEmitter(&events))

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE1,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if !errors.Is(err, generateErr) {
		t.Fatalf("Expected Generate error %v, got %v", generateErr, err)
	}
	if resp.Response != "" || resp.Handled {
		t.Fatalf("Generate error should not produce fallback success response: %#v", resp)
	}
	if _, ok := findCodeExecutorEvent(events, "agent.response", "shiro", "mio"); ok {
		t.Fatalf("Generate error should not emit shiro->mio success response: %#v", events)
	}
	if _, ok := findCodeExecutorEvent(events, "agent.response", "coder1", "shiro"); !ok {
		t.Fatalf("Generate error should emit coder->shiro error evidence: %#v", events)
	}
}

// TestCodeExecutor_CODE_GenericRoute_Fallback はCODE汎用ルートのフォールバックテスト
func TestCodeExecutor_CODE_GenericRoute_Fallback(t *testing.T) {
	// coder1がnilの場合にcoder2にフォールバック
	coder2 := &mockCoderAgent{response: "CODE2 fallback response"}

	executor := NewDefaultCodeExecutor(nil, coder2, nil, nil, nil, nil, noopEventEmitter)

	jobID := task.NewJobID()
	req := CodeExecutionRequest{
		Task:      task.NewTask(jobID, "user message", "test", "chat-1"),
		Route:     routing.RouteCODE,
		SessionID: "sess-1",
		Channel:   "test",
		ChatID:    "chat-1",
		JobID:     jobID.String(),
	}

	resp, err := executor.ExecuteCode(context.Background(), req)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}

	// coder1がnilならcoder2にフォールバック
	if resp.Response != "CODE2 fallback response" {
		t.Errorf("Expected fallback to coder2, got '%s'", resp.Response)
	}
}

// ヘルパー関数
func noopEventEmitter(eventType, from, to, content, route, jobID, sessionID, channel, chatID string) {
	// テスト用の空実装
}

type failingCoderAgent struct {
	err error
}

func (m *failingCoderAgent) Generate(ctx context.Context, t task.Task, systemPrompt string) (string, error) {
	return "", m.err
}

type codeExecutorEvent struct {
	eventType string
	from      string
	to        string
	content   string
	route     string
	jobID     string
	sessionID string
	channel   string
	chatID    string
}

func recordingCodeEventEmitter(events *[]codeExecutorEvent) func(eventType, from, to, content, route, jobID, sessionID, channel, chatID string) {
	return func(eventType, from, to, content, route, jobID, sessionID, channel, chatID string) {
		*events = append(*events, codeExecutorEvent{
			eventType: eventType,
			from:      from,
			to:        to,
			content:   content,
			route:     route,
			jobID:     jobID,
			sessionID: sessionID,
			channel:   channel,
			chatID:    chatID,
		})
	}
}

func findCodeExecutorEvent(events []codeExecutorEvent, eventType, from, to string) (codeExecutorEvent, bool) {
	for _, event := range events {
		if event.eventType == eventType && event.from == from && event.to == to {
			return event, true
		}
	}
	return codeExecutorEvent{}, false
}

type recordingCodeWorkerExecutionService struct {
	calls    int
	jobID    task.JobID
	proposal *proposal.Proposal
	err      error
}

func (s *recordingCodeWorkerExecutionService) ExecuteProposal(ctx context.Context, jobID task.JobID, p *proposal.Proposal) (*patch.PatchExecutionResult, error) {
	s.calls++
	s.jobID = jobID
	s.proposal = p
	if s.err != nil {
		return nil, s.err
	}
	result := patch.NewPatchExecutionResult()
	result.AddResult(patch.CommandResult{Success: true, Output: "ok"})
	return result.WithSummary("実行: 1 件, 成功: 1 件, 失敗: 0 件"), nil
}

type recordingCoderProposalEvidenceRecorder struct {
	items []domainskill.CoderProposalEvidence
	err   error
}

func (r *recordingCoderProposalEvidenceRecorder) SaveCoderProposalEvidence(_ context.Context, item domainskill.CoderProposalEvidence) (domainskill.CoderProposalEvidencePaths, error) {
	r.items = append(r.items, item)
	if r.err != nil {
		return domainskill.CoderProposalEvidencePaths{}, r.err
	}
	return domainskill.CoderProposalEvidencePaths{
		RootPath:            "workspace/logs/skill_governance/coder_evidence/job",
		SkillDiffPath:       "workspace/logs/skill_governance/coder_evidence/job/skill_diff.md",
		AgentTranscriptPath: "workspace/logs/skill_governance/coder_evidence/job/agent_transcript.md",
	}, nil
}
