package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"

	"github.com/Nyukimin/picoclaw_multiLLM/internal/adapter/config"
	"github.com/Nyukimin/picoclaw_multiLLM/internal/domain/agent"
	"github.com/Nyukimin/picoclaw_multiLLM/internal/domain/task"
	domaintransport "github.com/Nyukimin/picoclaw_multiLLM/internal/domain/transport"
)

// coderHandler はCoderエージェントのハンドラ
type coderHandler struct {
	agentName        string
	coderAgent       *agent.CoderAgent // Fallback agent (local config)
	proposalPrompt   string
	characterPrompts map[string]string
	globalMemory     *agent.LightMemory // 共有メモリ（SSH経由の場合は再利用）
}

func (h *coderHandler) HandleMessage(ctx context.Context, msg domaintransport.Message) (domaintransport.Message, error) {
	jobID, err := task.ParseJobID(msg.JobID)
	if err != nil {
		jobID = task.NewJobID()
	}

	t := task.NewTask(jobID, msg.Content, "standalone", "agent")

	// v4.1: Message.Context から CoderConfig を抽出して動的に Provider 作成
	activeAgent := h.coderAgent // デフォルトはローカル設定の Agent
	if msg.Context != nil {
		if coderCfgRaw, ok := msg.Context["coder_config"]; ok {
			// CoderConfig を復元
			coderCfg, err := extractCoderConfig(coderCfgRaw)
			if err != nil {
				log.Printf("[coderHandler] Failed to extract CoderConfig from Context: %v", err)
			} else {
				// CoderConfig から Provider を動的作成
				provider, err := createProviderFromConfig(coderCfg)
				if err != nil {
					log.Printf("[coderHandler] Failed to create provider from CoderConfig: %v", err)
				} else {
					// 一時的な CoderAgent を作成
					tempAgent := agent.NewCoderAgent(provider, nil, nil, h.proposalPrompt)

					// Persona 適用
					if personality := coderPersonalityFromCharacters(coderCfg, h.characterPrompts); personality != "" {
						persona := agent.AgentPersona{
							Name:        coderCfg.Name,
							Personality: personality,
							Tone:        coderCfg.Tone,
						}
						tempAgent.WithPersona(persona)
						log.Printf("[coderHandler] Applied Persona: %s", coderCfg.Name)
					}

					// LightMemory 適用（SSH 経由では共有インスタンス再利用）
					if coderCfg.LightMemory.Enabled {
						if h.globalMemory == nil {
							h.globalMemory = agent.NewLightMemory(coderCfg.LightMemory.MaxTurns)
						}
						tempAgent.WithLightMemory(h.globalMemory)
						log.Printf("[coderHandler] Applied LightMemory: max_turns=%d", coderCfg.LightMemory.MaxTurns)
					}

					activeAgent = tempAgent
					log.Printf("[coderHandler] Using remote CoderConfig: provider=%s, model=%s", coderCfg.Provider, coderCfg.Model)
				}
			}
		}
	}

	// CoderAgentでProposal生成
	p, err := activeAgent.GenerateProposal(ctx, t)
	if err != nil {
		errResp := domaintransport.NewMessage(msg.To, msg.From, msg.SessionID, msg.JobID,
			fmt.Sprintf("proposal generation failed: %v", err))
		errResp.Type = domaintransport.MessageTypeError
		return errResp, nil
	}

	if p == nil {
		errResp := domaintransport.NewMessage(msg.To, msg.From, msg.SessionID, msg.JobID,
			"proposal generation returned empty result (invalid format)")
		errResp.Type = domaintransport.MessageTypeError
		return errResp, nil
	}

	response := domaintransport.NewMessage(msg.To, msg.From, msg.SessionID, msg.JobID,
		fmt.Sprintf("Proposal generated by %s", h.agentName))
	response.Type = domaintransport.MessageTypeResult
	response.Proposal = &domaintransport.ProposalPayload{
		Plan:     p.Plan(),
		Patch:    p.Patch(),
		Risk:     p.Risk(),
		CostHint: p.CostHint(),
	}

	return response, nil
}

// extractCoderConfig は Message.Context から CoderConfig を抽出
func extractCoderConfig(raw interface{}) (config.CoderConfig, error) {
	// JSON 経由で送られてくるため、map[string]interface{} として扱う
	cfgMap, ok := raw.(map[string]interface{})
	if !ok {
		return config.CoderConfig{}, fmt.Errorf("coder_config is not a map")
	}

	// JSON として再エンコード → デコード
	jsonBytes, err := json.Marshal(cfgMap)
	if err != nil {
		return config.CoderConfig{}, fmt.Errorf("failed to marshal coder_config: %w", err)
	}

	var coderCfg config.CoderConfig
	if err := json.Unmarshal(jsonBytes, &coderCfg); err != nil {
		return config.CoderConfig{}, fmt.Errorf("failed to unmarshal coder_config: %w", err)
	}

	return coderCfg, nil
}
