import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';

test('viewer exposes memory inspector and news pack UI hooks', () => {
  const html = fs.readFileSync('internal/adapter/viewer/viewer.html', 'utf8');
  const js = fs.readFileSync('internal/adapter/viewer/assets/js/viewer.js', 'utf8');
  const viewer = html + '\n' + js;
  assert.match(html, /data-tab="memory"/);
  assert.match(html, /id="panel-memory"/);
  assert.match(html, /class="theme-modern"/);
  assert.match(html, /class="theme-switcher"/);
  assert.match(html, /data-theme="classic"/);
  assert.match(html, /data-theme="modern"/);
  assert.match(html, /data-theme="compact"/);
  assert.match(html, /id="mobilePanelSelect"/);
  assert.match(html, /id="mobilePanelPrev"/);
  assert.match(html, /id="mobilePanelNext"/);
  assert.match(html, /<option value="idlechat">IdleChat<\/option>/);
  assert.match(html, /id="memoryNamespace"/);
  assert.match(html, /id="memorySession"/);
  assert.match(html, /id="memoryLayerBody"/);
  assert.match(html, /id="memoryEventBody"/);
  assert.match(html, /id="searchCacheBody"/);
  assert.match(html, /id="memoryPromoteKind"/);
  assert.match(html, /id="memoryPromoteID"/);
  assert.match(html, /id="sourceRegistryBody"/);
  assert.match(html, /id="sourceRegistryYAML"/);
  assert.match(html, /id="memoryBody"/);
  assert.match(html, /id="newsPackBody"/);
  assert.match(html, /id="llmMemoryCards"/);
  assert.match(html, /id="llmMemorySystemBar"/);
  assert.match(html, /id="llmMemoryRoles"/);
  assert.match(html, /id="llmRuntimeConfigCards"/);
  assert.match(html, /id="llmOpsConfigState"/);
  assert.match(html, /data-tab="news-pack"/);
  assert.match(html, /id="panel-news-pack"/);
  assert.match(html, /id="newsPackDetail"/);
  assert.match(html, /id="newsUsageBody"/);
  assert.match(html, /id="recallTraceBody"/);
  assert.match(html, /<th>Decision<\/th>/);
  assert.match(html, /<th>Reason<\/th>/);
  assert.match(js, /item\.Decision/);
  assert.match(js, /item\.Reason/);
  assert.match(js, /function refreshMemorySnapshot/);
  assert.match(js, /function refreshNewsPack/);
  assert.match(js, /function renderNewsPackPanel/);
  assert.match(js, /function newsUsageCount/);
  assert.match(js, /function newsRelatedMemoryMatches/);
  assert.match(html, /id="newsRelatedMemoryBody"/);
  assert.match(js, /function refreshMemoryLayers/);
  assert.match(js, /function refreshMemoryEvents/);
  assert.match(js, /function renderMemoryEvents/);
  assert.match(js, /function applyViewerTheme/);
  assert.match(js, /viewer\.theme/);
  assert.match(js, /function switchAdjacentPanel/);
  assert.match(js, /mobilePanelSelect\.addEventListener\('change'/);
  assert.match(js, /function renderLlmMemoryStatus/);
  assert.match(js, /function renderLocalLLMRuntimeConfig/);
  assert.match(js, /\/v1\/chat\/completions/);
  assert.match(js, /llm_ops_configured/);
  assert.match(js, /LLM_OPS_TOKEN missing/);
  assert.match(js, /memory\.system/);
  assert.match(js, /memory\.llm_by_role/);
  assert.match(js, /function refreshSourceRegistry/);
  assert.match(js, /function runSourceRegistryEntry/);
  assert.match(js, /function refreshRecallTraces/);
  assert.match(html, /data-tab="roles"/);
  assert.match(html, /id="panel-roles"/);
  assert.match(html, /id="roleSelectorBody"/);
  assert.match(html, /id="roleFilter"/);
  assert.match(js, /const ROLE_TARGETS/);
  assert.match(js, /function renderRoleSelector/);
  assert.match(js, /function selectRoleTarget/);
  assert.match(js, /function applyRoleTargetToMessage/);
  assert.match(html, /Chat/);
  assert.match(html, /Worker/);
  assert.match(html, /Wild/);
  assert.ok(js.includes("return '/ops ' + trimmed"));
  assert.ok(js.includes("return '/wild ' + trimmed"));
  assert.ok(js.includes("return '/code2 ' + trimmed"));
  assert.ok(js.includes("return '/code3 ' + trimmed"));
  assert.ok(js.includes("return '/code4 ' + trimmed"));
  assert.ok(viewer.includes('/viewer/memory/snapshot'));
  assert.ok(viewer.includes('/viewer/memory/layers'));
  assert.ok(viewer.includes('/viewer/memory/events'));
  assert.ok(viewer.includes('/viewer/source-registry'));
  assert.ok(viewer.includes('/viewer/recall/traces'));
  assert.ok(viewer.includes('/viewer/memory/state'));
  assert.ok(viewer.includes('/viewer/memory/promote'));
  assert.ok(viewer.includes('target_kind'));
  assert.ok(viewer.includes('target_id'));
});
