package idlechat

type StoryTwistSeed struct {
	VisibleTwist    string
	Setting         string
	Viewpoint       string
	ImmediateChange string
	ConflictShift   string
	EndingShape     string
	EndingFlavor    string
	StoryTitle      string
	Hook            string
	Tone            string
}

type StorySpec struct {
	Skeleton StorySkeleton
	Twists   map[string][]StoryTwistSeed
}

func storyBeat(id, label string, canonical []string, subs ...string) StoryBeat {
	return StoryBeat{ID: id, Label: label, Canonical: canonical, Required: true, AllowedSubstitute: subs}
}

func storySpecForSource(source StorySource) (StorySpec, bool) {
	spec, ok := storySpecs[source.ID]
	if !ok {
		return StorySpec{}, false
	}
	spec.Skeleton.ID = source.ID
	spec.Skeleton.SourceTitle = source.Title
	return spec, true
}

func chooseStorySpecTwist(source StorySource, style string) (StoryTwist, bool) {
	spec, ok := storySpecForSource(source)
	if !ok {
		return StoryTwist{}, false
	}
	seeds := spec.Twists[normalizeStoryRewriteStyle(style)]
	if len(seeds) == 0 {
		return StoryTwist{}, false
	}
	seed := seeds[storyRandIntn(len(seeds))]
	return StoryTwist{
		Style:           normalizeStoryRewriteStyle(style),
		VisibleTwist:    seed.VisibleTwist,
		Setting:         seed.Setting,
		Viewpoint:       seed.Viewpoint,
		ImmediateChange: seed.ImmediateChange,
		ConflictShift:   seed.ConflictShift,
		EndingShape:     seed.EndingShape,
		EndingFlavor:    seed.EndingFlavor,
		StoryTitle:      seed.StoryTitle,
		Hook:            seed.Hook,
		Tone:            seed.Tone,
	}, true
}

var storySpecs = map[string]StorySpec{
	"momotaro": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"桃から生まれる", "きびだんご", "犬猿雉", "鬼ヶ島", "宝を持ち帰る"},
			RoleConstraints:     []string{"育てられた主役", "同行する三人の仲間", "島で搾取する対立役", "帰還を待つ村"},
			TabooOrRule:         "独りの手柄にせず、与えたものの縁を裏切らないこと",
			RewardPunishment:    "分け与えた信頼が勝利を呼び、奪う側は拠点ごと失う",
			EmotionalAftertaste: "連帯の熱と戦いの荒さが同時に残る",
			RecognitionCues:     []string{"桃", "きびだんご", "犬", "猿", "雉", "鬼ヶ島"},
			RequiredBeats: []StoryBeat{
				storyBeat("birth", "異様な出発", []string{"桃", "生まれる"}, "拾われる", "現れる"),
				storyBeat("recruit", "仲間集め", []string{"きびだんご", "犬", "猿", "雉"}, "配る", "従える"),
				storyBeat("raid", "島への踏み込み", []string{"鬼ヶ島", "鬼"}, "拠点", "踏み込む"),
				storyBeat("return", "宝を持ち帰る", []string{"宝", "持ち帰る"}, "回収", "帰還"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『桃太郎』を、拾われた新人監査役が小さな手土産で協力者を集め、湾岸倉庫の搾取拠点に踏み込む話へ置き換える",
				Setting:         "再開発前の湾岸物流地区",
				Viewpoint:       "突然抜てきされた新人監査役の近接三人称",
				ImmediateChange: "冒頭で、場違いな新人が奇妙な採用経路で現場へ送り込まれる",
				ConflictShift:   "怪物退治ではなく、配った小さな信頼で仲間を束ねて島のような拠点を崩せるかが争点になる",
				EndingShape:     "回収した証拠と金の重さより、誰と帰れたかが残る終わり",
				EndingFlavor:    "救い",
				StoryTitle:      "湾岸の桃太郎",
				Hook:            "『桃太郎』を、奇妙な新人が小さな配り物で協力者を増やす現代の踏み込み劇にすると、連帯の温度が変わる。",
				Tone:            "勢いと連帯感のある現代冒険譚",
			}},
			"view_shift": {{
				VisibleTwist:    "『桃太郎』を、きびだんごで雇われた最初の仲間の視点から語り、英雄の正しさに少し疑いを混ぜる",
				Setting:         "港と倉庫が連なる水辺の町",
				Viewpoint:       "最初に雇われた現場の相棒の一人称",
				ImmediateChange: "最初に、主人公の正義よりも報酬と違和感に引かれてついていった本音を明かす",
				ConflictShift:   "鬼退治より、誰のための遠征なのかを見定める話になる",
				EndingShape:     "勝ったあとで、持ち帰ったものの分け前より傷の共有が残る終わり",
				EndingFlavor:    "喪失",
				StoryTitle:      "きびだんごを受け取った犬",
				Hook:            "『桃太郎』は、最初の仲間の目には勧誘と取引の匂いがもっと濃く見えていた。",
				Tone:            "少し乾いた相棒目線の語り",
			}},
			"value_shift": {{
				VisibleTwist:    "『桃太郎』のきびだんごを、忠誠ではなく借りを作る契約の印として読み替える",
				Setting:         "成果主義の強い外郭団体と下請け網",
				Viewpoint:       "配られた側の一人称",
				ImmediateChange: "冒頭で、小さな手土産が善意ではなく、後で逆らえなくなる印として渡される",
				ConflictShift:   "鬼退治より、恩義と拘束の境目を見抜けるかが争点になる",
				EndingShape:     "敵を倒しても、配られたものの負債だけが残る終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "返せないきびだんご",
				Hook:            "『桃太郎』で配られた小さな食べ物が、忠誠ではなく借りの印だったら。 ",
				Tone:            "少し苦い現代寓話",
			}},
		},
	},
	"urashima": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"亀を助ける", "竜宮城", "玉手箱", "時間のずれ"},
			RoleConstraints:     []string{"助ける若者", "導く相手", "禁を託す存在", "帰還後の世界"},
			TabooOrRule:         "託された禁を破らないこと",
			RewardPunishment:    "好奇心の代償が、帰還後に一気に押し寄せる",
			EmotionalAftertaste: "取り返せない時間が胸に残る",
			RecognitionCues:     []string{"亀", "竜宮城", "玉手箱", "時間"},
			RequiredBeats: []StoryBeat{
				storyBeat("rescue", "弱い相手を助ける", []string{"亀", "助ける"}, "庇う"),
				storyBeat("invite", "別世界へ招かれる", []string{"竜宮城", "招かれる"}, "奥の空間", "歓待"),
				storyBeat("taboo", "禁を託される", []string{"玉手箱", "開けるな"}, "封筒", "触れるな"),
				storyBeat("return", "帰還と時間差", []string{"戻る", "時間"}, "帰る", "空白"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『浦島太郎』を、炎上案件から一人を救った若手相談員が、閉じた上級コミュニティへ招かれ、封筒を開けた瞬間に居場所を失う話に置き換える",
				Setting:         "海辺の観光地と会員制の保養施設",
				Viewpoint:       "人助けの延長で巻き込まれた若手相談員の一人称",
				ImmediateChange: "冒頭で、主人公は路上で追い詰められた相手をかばい、予想外の招待状を受け取る",
				ConflictShift:   "幻想体験より、禁を守れば帰れるのか、守っても戻れないのかが争点になる",
				EndingShape:     "開けた瞬間に失われた年月より、戻れない関係が重く残る終わり",
				EndingFlavor:    "喪失",
				StoryTitle:      "封筒を開けた浦島",
				Hook:            "『浦島太郎』を、救助のあとに閉じた保養施設へ招かれる現代話にすると、禁の意味がもっと冷たく効く。",
				Tone:            "静かな違和感が積もる現代奇譚",
			}},
			"view_shift": {{
				VisibleTwist:    "『浦島太郎』を、助けられた側の視点から語り、招待そのものが返礼であり罠でもあったことを明かす",
				Setting:         "海辺の保養施設と退避用ラウンジ",
				Viewpoint:       "救われたあと主人公を導いた側の一人称",
				ImmediateChange: "最初に、招待は恩返しだけでなく距離を置くためでもあったと告白する",
				ConflictShift:   "楽園の魅力より、連れ込んだ相手をどう返すかが争点になる",
				EndingShape:     "帰したあとで、その人の時間だけが壊れたことを見届ける終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "亀が返した時間",
				Hook:            "『浦島太郎』は、助けられた側から見ると返礼と隔離の境目が曖昧だった。",
				Tone:            "内省的で少し痛みのある語り",
			}},
			"value_shift": {{
				VisibleTwist:    "『浦島太郎』の返礼を、救われた恩に見せかけた長期拘束の契約として反転させる",
				Setting:         "福利厚生が過剰な会員制企業",
				Viewpoint:       "厚遇を受ける側の一人称",
				ImmediateChange: "冒頭で、ありがたいはずの招待が日常を奪う条件付きだと分かる",
				ConflictShift:   "禁を破る好奇心ではなく、受けた恩からどう離脱するかが争点になる",
				EndingShape:     "玉手箱に相当する封印を解いたあと、救いではなく負債の清算だけが残る終わり",
				EndingFlavor:    "報い",
				StoryTitle:      "返礼の玉手箱",
				Hook:            "『浦島太郎』でもらった返礼が、開けた瞬間に借りへ変わるとしたら。",
				Tone:            "冷えた現代寓話",
			}},
		},
	},
	"kaguya": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"光る竹", "かぐや姫", "無理難題の求婚", "月へ帰る"},
			RoleConstraints:     []string{"拾われた姫", "育てる老夫婦", "難題を出される求婚者", "連れ戻す月の側"},
			TabooOrRule:         "所有したい気持ちで相手の出自と選択を奪わないこと",
			RewardPunishment:    "執着は見送るしかない別れへ変わる",
			EmotionalAftertaste: "手の届かなさが美しさと一緒に残る",
			RecognitionCues:     []string{"竹", "姫", "難題", "月"},
			RequiredBeats: []StoryBeat{
				storyBeat("find", "異様な発見", []string{"竹", "光"}, "見つける", "拾う"),
				storyBeat("court", "難題を課す求婚", []string{"難題", "求婚"}, "条件", "試す"),
				storyBeat("reveal", "帰属が明かされる", []string{"月", "迎え"}, "本来の場所", "連れ戻す"),
				storyBeat("depart", "見送る別れ", []string{"帰る", "別れ"}, "去る", "見送る"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『竹取物語』を、研究施設で保護された天才少女が無理難題で後援者を遠ざけ、最後に契約ごと引き戻される話へ置き換える",
				Setting:         "地方研究所と都心の支援ネットワーク",
				Viewpoint:       "保護者代わりの所長の近接三人称",
				ImmediateChange: "冒頭で、ありえない才能を持つ少女が異様な経路で保護される",
				ConflictShift:   "恋愛より、誰も彼女を所有できないまま条件だけが積み上がる話になる",
				EndingShape:     "引き留めるほど離れていく別れが残る終わり",
				EndingFlavor:    "喪失",
				StoryTitle:      "研究棟のかぐや姫",
				Hook:            "『竹取物語』を、保護された天才少女と支援者たちの距離の話に置き換えると、別れの冷たさがより現代的になる。",
				Tone:            "美しさの裏に距離がある語り",
			}},
			"view_shift": {{
				VisibleTwist:    "『竹取物語』を、難題を突きつけられた求婚者の視点から語り、試される側の滑稽さと執着を見せる",
				Setting:         "メディア露出の多い支援コミュニティ",
				Viewpoint:       "条件を課された支援者の一人称",
				ImmediateChange: "最初に、求めたのは愛情より名誉だったと認める",
				ConflictShift:   "姫を得る話ではなく、失敗しても執着をやめられるかが争点になる",
				EndingShape:     "去ったあとで、自分が試されていたと気づいて終わる",
				EndingFlavor:    "皮肉",
				StoryTitle:      "難題を受けた男",
				Hook:            "『竹取物語』は、難題を出された側から見ると欲と見栄の記録でもある。",
				Tone:            "少し滑稽で苦い一人称",
			}},
			"value_shift": {{
				VisibleTwist:    "『竹取物語』の求婚競争を、支援と保護の名で人を囲い込む評価ゲームとして反転させる",
				Setting:         "助成金とメディア評価が支配する文化事業",
				Viewpoint:       "囲い込まれる側の一人称",
				ImmediateChange: "冒頭で、好意に見えた支援の数々が選択肢を奪う圧になると分かる",
				ConflictShift:   "求愛より、誰の支援も受けずに去れるかが争点になる",
				EndingShape:     "見送る者たちの立派な顔だけが残る終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "月へ返す契約",
				Hook:            "『竹取物語』のきらびやかな求婚を、囲い込みのゲームとして読むと急に息苦しくなる。",
				Tone:            "上品だが刺すような現代寓話",
			}},
		},
	},
	"issun": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"小さな体", "針の刀", "椀の舟", "鬼の腹", "打ち出の小槌"},
			RoleConstraints:     []string{"小さな主役", "守る姫", "巨大な対立役", "成長を可能にする道具"},
			TabooOrRule:         "小ささを恥じて機転を捨てないこと",
			RewardPunishment:    "弱さを知恵に変えた者が最後に伸びる",
			EmotionalAftertaste: "小さな勇気が急に大きく見える",
			RecognitionCues:     []string{"一寸", "針", "椀", "小槌", "鬼"},
			RequiredBeats: []StoryBeat{
				storyBeat("depart", "小さな旅立ち", []string{"小さな体", "椀"}, "小舟", "旅立つ"),
				storyBeat("serve", "姫のそばで働く", []string{"姫", "仕える"}, "守る", "仕える"),
				storyBeat("fight", "巨大な相手の内側で戦う", []string{"鬼", "腹"}, "中から", "暴れる"),
				storyBeat("grow", "小槌で変わる", []string{"小槌", "大きくなる"}, "伸びる", "変わる"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『一寸法師』を、体格も立場も小さなインターンが、針のような細い道具だけで大組織の内部不正に食い込む話へ置き換える",
				Setting:         "老舗企業の本社と地下の保守区画",
				Viewpoint:       "小柄で軽んじられるインターンの一人称",
				ImmediateChange: "冒頭で、主役は誰にも数に入れられていないまま重要部署へ紛れ込む",
				ConflictShift:   "正面衝突ではなく、巨大な組織の内側から穴を開けられるかが争点になる",
				EndingShape:     "急に評価が変わっても、小さかった時の記憶が残る終わり",
				EndingFlavor:    "救い",
				StoryTitle:      "一寸のインターン",
				Hook:            "『一寸法師』を、軽く扱われるインターンが極細の道具だけで組織の内部へ潜る話にすると、小ささが武器に見えてくる。",
				Tone:            "軽快で痛快な現代活劇",
			}},
			"view_shift": {{
				VisibleTwist:    "『一寸法師』を、守られる側の視点から語り、小さな人物の無謀さと信頼を見つめ直す",
				Setting:         "危機管理が甘い上流組織の邸宅",
				Viewpoint:       "守られる立場にいた女性の一人称",
				ImmediateChange: "最初に、頼りなく見えた相手しか信じられなかった夜だと打ち明ける",
				ConflictShift:   "英雄誕生より、見えにくい働きを誰が見抜くかが争点になる",
				EndingShape:     "大きくなった後より、小さかった時の働きが胸に残る終わり",
				EndingFlavor:    "救い",
				StoryTitle:      "姫が見た一寸",
				Hook:            "『一寸法師』は、守られる側から見ると小さな無茶の連続だった。",
				Tone:            "やわらかな敬意のある回想",
			}},
			"value_shift": {{
				VisibleTwist:    "『一寸法師』の成長を、評価の爆上がりと引き換えに小さな自由を失う物語へ反転させる",
				Setting:         "成果だけで人を測る企業文化",
				Viewpoint:       "急に出世させられた本人の一人称",
				ImmediateChange: "冒頭で、認められたはずの瞬間から身動きが取れなくなる",
				ConflictShift:   "大きくなる喜びより、小さいままで持っていた機転を失わないかが争点になる",
				EndingShape:     "成功したはずなのに、以前の身軽さを恋しがって終わる",
				EndingFlavor:    "喪失",
				StoryTitle:      "大きくなった一寸",
				Hook:            "『一寸法師』のご褒美が、自由を失う昇進だったらどうなるか。",
				Tone:            "少し苦い成長譚",
			}},
		},
	},
	"hanasaka": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"犬が宝を示す", "欲深い隣人", "灰で花を咲かせる", "殿様に喜ばれる"},
			RoleConstraints:     []string{"優しい老夫婦", "宝を示す相棒", "欲深い対比役", "見届ける権力者"},
			TabooOrRule:         "他人の幸運を奪うために相棒を使い潰さないこと",
			RewardPunishment:    "慈しみは花を咲かせ、欲は自分の手を汚す",
			EmotionalAftertaste: "失った相棒の悲しみの上に小さな華やぎが残る",
			RecognitionCues:     []string{"犬", "灰", "花", "隣人"},
			RequiredBeats: []StoryBeat{
				storyBeat("find", "相棒が宝を示す", []string{"犬", "宝"}, "掘る", "見つける"),
				storyBeat("steal", "欲深い隣人が真似る", []string{"隣人", "欲深い"}, "まねる", "奪う"),
				storyBeat("ash", "灰を得る", []string{"灰"}, "焼け跡", "残り"),
				storyBeat("bloom", "花が咲く", []string{"花", "咲く"}, "満開", "喜ばれる"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『花咲かじいさん』を、地域で信頼される清掃員と保護犬が埋もれた証拠を見つけ、欲深い隣店主がそれを食い潰す話へ置き換える",
				Setting:         "下町商店街と再開発予定地",
				Viewpoint:       "保護犬と働く清掃員の近接三人称",
				ImmediateChange: "冒頭で、誰にも注目されない相棒が最初の手がかりを掘り当てる",
				ConflictShift:   "奇跡より、相棒を慈しむか利用するかの差が争点になる",
				EndingShape:     "失った相棒の不在の上に、遅れて花が咲く終わり",
				EndingFlavor:    "救い",
				StoryTitle:      "灰から咲く通り",
				Hook:            "『花咲かじいさん』を、保護犬が見つけた証拠から始まる下町の話に置き換えると、優しさと欲の差がよく見える。",
				Tone:            "温かさと喪失が同居する語り",
			}},
			"view_shift": {{
				VisibleTwist:    "『花咲かじいさん』を、欲深い隣人の視点から語り、自分で壊した縁が最後に花として戻る皮肉を見る",
				Setting:         "隣り合う個人商店",
				Viewpoint:       "隣店主の一人称",
				ImmediateChange: "最初に、羨みから真似たと自分で認める",
				ConflictShift:   "奇跡を得る話ではなく、壊したものの重さを見続ける話になる",
				EndingShape:     "他人の通りだけが花で明るくなるのを見て終わる",
				EndingFlavor:    "皮肉",
				StoryTitle:      "隣で咲いた花",
				Hook:            "『花咲かじいさん』は、隣人の目には他人の徳がまぶしすぎる記録だった。",
				Tone:            "苦味の強い告白調",
			}},
			"value_shift": {{
				VisibleTwist:    "『花咲かじいさん』の賞賛を、善人だけに押しつけられる奉仕の圧力として反転させる",
				Setting:         "地域貢献が評価指標になる自治会",
				Viewpoint:       "褒められ続ける側の一人称",
				ImmediateChange: "冒頭で、拍手が義務の始まりでもあると分かる",
				ConflictShift:   "欲深さとの対比より、善人役を降りられるかが争点になる",
				EndingShape:     "花が咲いても、次も咲かせろという声だけが増える終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "咲かされる人",
				Hook:            "『花咲かじいさん』の拍手が、休ませてくれない圧力だったら。",
				Tone:            "静かな息苦しさのある現代寓話",
			}},
		},
	},
	"shitakiri": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"舌を切る", "小さいつづら", "大きいつづら", "欲深さの報い"},
			RoleConstraints:     []string{"優しい与え手", "欲深い対比役", "恩返しする雀", "選択を迫る贈り物"},
			TabooOrRule:         "相手の尊厳を傷つけず、欲で選ばないこと",
			RewardPunishment:    "控えめさは報われ、欲深さは自滅に変わる",
			EmotionalAftertaste: "欲と慎みの差が静かに痛む",
			RecognitionCues:     []string{"雀", "舌", "小さいつづら", "大きいつづら"},
			RequiredBeats: []StoryBeat{
				storyBeat("hurt", "尊厳を傷つける", []string{"舌を切る", "傷つける"}, "声を奪う"),
				storyBeat("hospitality", "恩返しのもてなし", []string{"恩返し", "招待"}, "もてなし", "返礼"),
				storyBeat("small", "小さい選択", []string{"小さいつづら", "小さな箱"}, "控えめ"),
				storyBeat("large", "大きい選択と報い", []string{"大きいつづら", "報い"}, "大きな箱", "自滅"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『舌切り雀』を、発言権を奪われた若い配信者が静かな返礼を用意し、控えめな選択と過剰な選択の差で人間関係を裁く話へ置き換える",
				Setting:         "地域配信スタジオと古い住宅街",
				Viewpoint:       "失言処分を目撃した年配の支援者の一人称",
				ImmediateChange: "冒頭で、軽く扱われた一言が相手の声ごと奪う処分になる",
				ConflictShift:   "怪異より、相手の尊厳を踏んだあとにどんな返礼が返るかが争点になる",
				EndingShape:     "小さな選択だけが救いになり、大きい選択は崩れる終わり",
				EndingFlavor:    "報い",
				StoryTitle:      "小さい箱の返礼",
				Hook:            "『舌切り雀』を、声を奪う処分と二つの箱の選択の話として現代へ置くと、欲の輪郭が鋭くなる。",
				Tone:            "静かな寓話性のある語り",
			}},
			"view_shift": {{
				VisibleTwist:    "『舌切り雀』を、恩返しを用意する側の視点から語り、誰にどの箱を渡すかの迷いを見せる",
				Setting:         "裏通りの小さな作業場",
				Viewpoint:       "声を傷つけられた側の一人称",
				ImmediateChange: "最初に、復讐ではなく相手の選び方を試すつもりだと明かす",
				ConflictShift:   "人間の欲をどう見極めるかが争点になる",
				EndingShape:     "大きい箱を選ばせたあとでも少し痛みが残る終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "雀が渡した箱",
				Hook:            "『舌切り雀』は、返礼を渡す側から見ると試験に近かった。",
				Tone:            "静かだが厳しい一人称",
			}},
			"value_shift": {{
				VisibleTwist:    "『舌切り雀』の報酬を、相手を見極める査定装置として読み替え、贈り物そのものに善悪を入れない",
				Setting:         "支援制度と寄付文化が交差する街",
				Viewpoint:       "箱を受け取る側の一人称",
				ImmediateChange: "冒頭で、贈り物はご褒美ではなく選び方を映す鏡だと分かる",
				ConflictShift:   "もらえるかより、自分がどちらを選ぶ人間かが争点になる",
				EndingShape:     "箱の中身より選んだ手つきが忘れられない終わり",
				EndingFlavor:    "報い",
				StoryTitle:      "つづらの査定",
				Hook:            "『舌切り雀』の二つのつづらが、人を映す査定装置だったら。",
				Tone:            "冷えた倫理寓話",
			}},
		},
	},
	"kasajizo": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"年の暮れの困窮", "売れ残りの笠", "六体の地蔵", "足りない一体に手ぬぐい", "夜の返礼", "温かな正月"},
			RoleConstraints:     []string{"貧しい老夫婦", "売れない荷を抱えた与え手", "寒さに立つ地蔵", "夜に返礼する見えない手"},
			TabooOrRule:         "見返りを求めて施しをしないこと",
			RewardPunishment:    "差し出した温もりが、静かな返礼として戻る",
			EmotionalAftertaste: "寒さのあとに来る温かさが静かに残る",
			RecognitionCues:     []string{"笠", "地蔵", "手ぬぐい", "年の暮れ", "正月"},
			RequiredBeats: []StoryBeat{
				storyBeat("poverty", "年の暮れの困窮と売れ残り", []string{"年の暮れ", "売れ残り"}, "笠", "寒い"),
				storyBeat("offer", "地蔵に笠をかぶせる", []string{"地蔵", "笠"}, "かぶせる", "贈る"),
				storyBeat("cloth", "足りない一体に手ぬぐいを巻く", []string{"手ぬぐい", "足りない"}, "布を巻く"),
				storyBeat("return", "夜の返礼と温かな正月", []string{"夜", "返礼", "正月"}, "贈り物", "朝"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『笠地蔵』を、年末の路上支援で売れ残った防寒具を地蔵堂へ置いて帰った老夫婦に、夜のうち静かな返礼が届く話へ置き換える",
				Setting:         "雪の降る門前町と小さな地蔵堂",
				Viewpoint:       "売れ残りを抱えた高齢の露店主の一人称",
				ImmediateChange: "冒頭で、年の瀬の売上が立たず、正月を越せない寒さが先に来る",
				ConflictShift:   "奇跡より、見返りなしの施しを最後まで貫けるかが争点になる",
				EndingShape:     "派手な成功ではなく、朝に届いた温かさで終わる",
				EndingFlavor:    "救い",
				StoryTitle:      "年の瀬の笠",
				Hook:            "『笠地蔵』を、年末の路上支援と売れ残りの防寒具の話にすると、返礼の静けさがよく響く。",
				Tone:            "しんとした寒さと温かさのある語り",
			}},
			"view_shift": {{
				VisibleTwist:    "『笠地蔵』を、家で待っていた妻の視点から語り、差し出す人の無茶と返ってくる温かさを見つめ直す",
				Setting:         "雪の夜の小さな家と門前通り",
				Viewpoint:       "帰りを待つ妻の一人称",
				ImmediateChange: "最初に、売れ残ったと聞いた時点で正月を諦めかけていたと明かす",
				ConflictShift:   "奇跡の発見より、誰にも見られない善意を信じ切れるかが争点になる",
				EndingShape:     "夜更けの物音が返礼だと分かる瞬間で終わる",
				EndingFlavor:    "救い",
				StoryTitle:      "笠を待つ夜",
				Hook:            "『笠地蔵』は、家で待つ者の目には寒さと諦めの物語として始まっていた。",
				Tone:            "静かな回想調",
			}},
			"value_shift": {{
				VisibleTwist:    "『笠地蔵』の返礼を、助け合いが可視化されて後から重荷にもなる地域支援の連鎖として反転させる",
				Setting:         "匿名寄付が地域アプリで拡散する雪国の町",
				Viewpoint:       "返礼を受ける側の一人称",
				ImmediateChange: "冒頭で、見返りを望まなかった行為が翌朝には町中に知れ渡る",
				ConflictShift:   "感謝より、善意が負債へ変わる手前で止まれるかが争点になる",
				EndingShape:     "温かい朝のあとに、返しきれない借りだけが残る終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "返礼の重み",
				Hook:            "『笠地蔵』の静かな返礼が、町中で可視化されてしまったら何が残るか。",
				Tone:            "温かさの裏に重さが差す現代寓話",
			}},
		},
	},
	"kintaro": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"怪力", "山の動物たち", "山で育つ", "都へ見いだされる"},
			RoleConstraints:     []string{"山で育つ主役", "共に遊ぶ動物たち", "才能を見いだす武士", "都へ送る母"},
			TabooOrRule:         "強さを誇示のためだけに使わないこと",
			RewardPunishment:    "大きな力は見いだされるが、居場所との別れを伴う",
			EmotionalAftertaste: "力の明るさと旅立ちの寂しさが残る",
			RecognitionCues:     []string{"金太郎", "山", "動物", "怪力", "都"},
			RequiredBeats: []StoryBeat{
				storyBeat("grow", "山で育つ", []string{"山", "育つ"}, "足柄", "母"),
				storyBeat("play", "動物と力比べ", []string{"動物", "力比べ"}, "熊", "相撲"),
				storyBeat("notice", "怪力を見いだされる", []string{"怪力", "見いだされる"}, "評判", "武士"),
				storyBeat("depart", "都へ向かう", []string{"都", "行く"}, "旅立つ"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『金太郎』を、山間の土木現場で育った怪力の少年が、地域の動物保護活動を通じて都心のレスキュー組織に見いだされる話へ置き換える",
				Setting:         "山間の作業道と災害対応訓練所",
				Viewpoint:       "母と暮らす少年の近接三人称",
				ImmediateChange: "冒頭で、主役は人より先に倒木を持ち上げてしまう",
				ConflictShift:   "腕比べより、力をどこへ向けるかが争点になる",
				EndingShape:     "晴れやかな旅立ちの裏に、山を離れる寂しさが残る終わり",
				EndingFlavor:    "喪失",
				StoryTitle:      "山の金太郎",
				Hook:            "『金太郎』を、山の怪力が都市のレスキューに拾われる話にすると、旅立ちが少し苦く見える。",
				Tone:            "明るさのある成長譚",
			}},
			"view_shift": {{
				VisibleTwist:    "『金太郎』を、山で遊んでいた動物の視点から語り、力のある友を都へ送り出す喪失を描く",
				Setting:         "山の遊び場と川沿いの小道",
				Viewpoint:       "いつも一緒にいた動物側の一人称",
				ImmediateChange: "最初に、強さよりも一緒に遊べなくなる怖さを明かす",
				ConflictShift:   "栄達より、送り出す側の寂しさが争点になる",
				EndingShape:     "去っていく背中を見届ける終わり",
				EndingFlavor:    "喪失",
				StoryTitle:      "熊が見送った金太郎",
				Hook:            "『金太郎』は、山に残る側から見ると友だちを失う話でもある。",
				Tone:            "やわらかな別れの語り",
			}},
			"value_shift": {{
				VisibleTwist:    "『金太郎』の怪力を、期待と消費の対象として扱われる才能へ反転させる",
				Setting:         "動画拡散とスカウトが渦巻く地方都市",
				Viewpoint:       "注目される少年の一人称",
				ImmediateChange: "冒頭で、褒められるたびに逃げ場がなくなる",
				ConflictShift:   "強さを見せる喜びより、見世物にされないかが争点になる",
				EndingShape:     "都へ行けても、山で無邪気に遊べた時間が戻らない終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "見いだされた怪力",
				Hook:            "『金太郎』の怪力が、祝福と同時に消費の対象でもあったら。",
				Tone:            "少し切ない現代成長譚",
			}},
		},
	},
	"sarukani": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"柿の種", "猿にだまされる", "親の仇討ち", "栗と蜂と臼"},
			RoleConstraints:     []string{"だまされる弱い側", "奪う猿", "復讐する子どもたち", "仕掛けを担う仲間"},
			TabooOrRule:         "目先の得で他者をだまさないこと",
			RewardPunishment:    "だました側は、積み上がった小さな怒りに囲まれて倒れる",
			EmotionalAftertaste: "復讐の達成と苦さが一緒に残る",
			RecognitionCues:     []string{"猿", "蟹", "柿", "栗", "蜂", "臼"},
			RequiredBeats: []StoryBeat{
				storyBeat("trade", "交換でだまされる", []string{"柿", "だます"}, "種", "交換"),
				storyBeat("loss", "親が倒される", []string{"仇", "死ぬ"}, "やられる"),
				storyBeat("allies", "仲間を集める", []string{"栗", "蜂", "臼"}, "仲間", "仕掛け"),
				storyBeat("revenge", "報復する", []string{"復讐", "報い"}, "仕返し"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『さるかに合戦』を、小さな商店が不利な交換でだまされ、遺された若者たちが仲間の細工で大企業幹部を追い詰める話へ置き換える",
				Setting:         "下町市場と食品流通会社",
				Viewpoint:       "店を継いだ子世代の一人称",
				ImmediateChange: "冒頭で、たった一度の不利な交換が店の運命を決めてしまう",
				ConflictShift:   "正面対決より、小さな仲間の仕掛けを重ねて報いに変える話になる",
				EndingShape:     "勝っても晴れない復讐の後味が残る終わり",
				EndingFlavor:    "報い",
				StoryTitle:      "柿の取引",
				Hook:            "『さるかに合戦』を、不利な交換から始まる商店街の復讐劇にすると、小さな仕掛けの集積が効いてくる。",
				Tone:            "勢いのある報復譚",
			}},
			"view_shift": {{
				VisibleTwist:    "『さるかに合戦』を、仕掛け役の一人の視点から語り、復讐が正義だけではないと見せる",
				Setting:         "報復の準備が進む古い倉庫",
				Viewpoint:       "細工を担う協力者の一人称",
				ImmediateChange: "最初に、助太刀のつもりでも心から晴れてはいないと明かす",
				ConflictShift:   "仇討ちの爽快さより、どこまでやるかの迷いが争点になる",
				EndingShape:     "報いは果たされても、胸が軽くならない終わり",
				EndingFlavor:    "喪失",
				StoryTitle:      "臼のそばにいた者",
				Hook:            "『さるかに合戦』は、助太刀した側から見ると復讐の熱と冷えが同時にある。",
				Tone:            "熱の奥に迷いがある語り",
			}},
			"value_shift": {{
				VisibleTwist:    "『さるかに合戦』の復讐を、被害者コミュニティが報いを制度に変える話として読み替える",
				Setting:         "告発と内部監査が広がる地域企業",
				Viewpoint:       "記録をまとめる当事者の一人称",
				ImmediateChange: "冒頭で、殴り返す代わりに記録を積むと決める",
				ConflictShift:   "私刑より、だましをどう公的な報いへ変えるかが争点になる",
				EndingShape:     "相手は倒れても、怒りが制度へ移っただけで終わる",
				EndingFlavor:    "皮肉",
				StoryTitle:      "柿の報告書",
				Hook:            "『さるかに合戦』の仕返しを、私刑ではなく制度化された報いに変えたらどうなるか。",
				Tone:            "冷静さのある現代寓話",
			}},
		},
	},
	"tsuru": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"助けた鶴", "機織り", "のぞいてはいけない", "正体が露見して去る"},
			RoleConstraints:     []string{"助ける人", "恩返しする鶴", "のぞく誘惑", "去られる家"},
			TabooOrRule:         "相手の秘密を成果のために暴かないこと",
			RewardPunishment:    "約束を守れば温もりが続き、破れば別れになる",
			EmotionalAftertaste: "得た暮らしより去った気配が残る",
			RecognitionCues:     []string{"鶴", "機織り", "のぞくな", "羽"},
			RequiredBeats: []StoryBeat{
				storyBeat("rescue", "助ける", []string{"助ける", "鶴"}, "救う"),
				storyBeat("weave", "機を織る", []string{"機織り", "布"}, "働く"),
				storyBeat("taboo", "のぞいてはいけない", []string{"のぞくな", "約束"}, "見るな"),
				storyBeat("depart", "正体露見と別れ", []string{"羽", "去る"}, "帰る", "別れ"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『鶴の恩返し』を、救われた若い職人が匿名で高価な制作物を作り続け、作業部屋をのぞかれた瞬間に去る話へ置き換える",
				Setting:         "雪国の小さな工房",
				Viewpoint:       "恩返しを受ける側の一人称",
				ImmediateChange: "冒頭で、助けた相手が現れたのに名乗らず働き始める",
				ConflictShift:   "儲けの話より、秘密を守る約束を守れるかが争点になる",
				EndingShape:     "暮らしは豊かになっても、作業音だけが消える終わり",
				EndingFlavor:    "喪失",
				StoryTitle:      "覗かなかった部屋",
				Hook:            "『鶴の恩返し』を、匿名の職人が高価な制作物を残して去る話にすると、秘密の重さが増す。",
				Tone:            "静かな冬の別離譚",
			}},
			"view_shift": {{
				VisibleTwist:    "『鶴の恩返し』を、恩返しする側の視点から語り、約束を守らせる難しさと去る決断を描く",
				Setting:         "外雪の工房と狭い作業部屋",
				Viewpoint:       "正体を隠して働く側の一人称",
				ImmediateChange: "最初に、別れが避けられない恩返しだと知っていたと明かす",
				ConflictShift:   "恩返しの美しさより、のぞかれた瞬間に終わる関係の儚さが争点になる",
				EndingShape:     "最後の一枚を残して出ていく終わり",
				EndingFlavor:    "喪失",
				StoryTitle:      "羽を織る夜",
				Hook:            "『鶴の恩返し』は、恩返しする側から見ると最初から別れを含んでいた。",
				Tone:            "静謐で透明感のある語り",
			}},
			"value_shift": {{
				VisibleTwist:    "『鶴の恩返し』の成果物を、相手の秘密を搾取して得る利益へ反転させる",
				Setting:         "一点物が高く売れるデザイン市場",
				Viewpoint:       "売る側の一人称",
				ImmediateChange: "冒頭で、売上が上がるほど秘密を暴きたい欲が強くなる",
				ConflictShift:   "愛情より、成果と秘密のどちらを守るかが争点になる",
				EndingShape:     "布は残っても、作り手だけが二度と戻らない終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "売れてしまった羽",
				Hook:            "『鶴の恩返し』の布が、相手の秘密を搾取して得る商品だったら。",
				Tone:            "冷えた商業寓話",
			}},
		},
	},
	"kobutori": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"こぶ", "鬼の宴", "踊り", "こぶを取る", "欲深い隣人"},
			RoleConstraints:     []string{"こぶのある老人", "宴を開く鬼", "真似る隣人", "結果を見る共同体"},
			TabooOrRule:         "他人の幸運を形だけ真似して奪おうとしないこと",
			RewardPunishment:    "自然体の芸は報われ、下心の模倣は重荷を増やす",
			EmotionalAftertaste: "滑稽さのあとに自業自得の苦さが残る",
			RecognitionCues:     []string{"こぶ", "鬼", "宴", "踊り"},
			RequiredBeats: []StoryBeat{
				storyBeat("shelter", "雨宿りと宴", []string{"雨宿り", "宴"}, "山小屋", "鬼"),
				storyBeat("dance", "踊りを見せる", []string{"踊り", "気に入られる"}, "芸"),
				storyBeat("remove", "こぶを取られる", []string{"こぶ", "取る"}, "外す"),
				storyBeat("imitate", "隣人が真似て失敗する", []string{"隣人", "もう一つ"}, "真似る", "増える"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『こぶとりじいさん』を、顔の傷を気にする年配の清掃員が深夜の打ち上げで即興芸を見せ、隣人の見栄がそれを台無しにする話へ置き換える",
				Setting:         "山間の作業小屋と深夜の作業員たちの宴",
				Viewpoint:       "傷のある清掃員の一人称",
				ImmediateChange: "冒頭で、隠していた傷を雨宿り先の宴で晒す羽目になる",
				ConflictShift:   "怪異より、自然体で笑われるか見栄で崩れるかが争点になる",
				EndingShape:     "自分の傷は軽くなっても、隣人の重さが増す終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "こぶを外した夜",
				Hook:            "『こぶとりじいさん』を、深夜の打ち上げで傷を笑いに変えてしまう年配者の話にすると、真似の苦さが際立つ。",
				Tone:            "滑稽さと人情のある語り",
			}},
			"view_shift": {{
				VisibleTwist:    "『こぶとりじいさん』を、真似した隣人の視点から語り、下心が芸を空っぽにする瞬間を見る",
				Setting:         "同じ山道と同じ作業小屋",
				Viewpoint:       "真似に失敗した隣人の一人称",
				ImmediateChange: "最初に、羨望しかなかったと認める",
				ConflictShift:   "こぶを取ることより、他人の自然さを真似できないことが争点になる",
				EndingShape:     "増えた重さだけを抱えて帰る終わり",
				EndingFlavor:    "報い",
				StoryTitle:      "増えたこぶ",
				Hook:            "『こぶとりじいさん』は、真似した側から見ると見栄と羨望の失敗談になる。",
				Tone:            "少し滑稽で痛い告白調",
			}},
			"value_shift": {{
				VisibleTwist:    "『こぶとりじいさん』の芸の評価を、共同体に都合よく消費される一発芸として反転させる",
				Setting:         "バズと消費が早い地域イベント文化",
				Viewpoint:       "その場で持ち上げられる側の一人称",
				ImmediateChange: "冒頭で、褒められること自体が利用される入口だと分かる",
				ConflictShift:   "こぶが取れる奇跡より、評価されるたびに自分が薄くなることが争点になる",
				EndingShape:     "傷は減っても、自分の芸が自分のものではなくなる終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "宴で取られたもの",
				Hook:            "『こぶとりじいさん』の拍手が、傷ではなく本人の輪郭を奪うものだったら。",
				Tone:            "現代的な苦みのある寓話",
			}},
		},
	},
	"bunbuku": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"狸が茶釜に化ける", "寺に売られる", "熱さに耐えられず逃げる", "見世物になる"},
			RoleConstraints:     []string{"助ける貧しい人", "化ける狸", "寺の和尚", "見世物の観客"},
			TabooOrRule:         "恩を金に換えるだけで相手の限界を無視しないこと",
			RewardPunishment:    "知恵を合わせれば暮らしは立つが、売り渡せば関係は壊れる",
			EmotionalAftertaste: "陽気さの裏に綱渡りの危うさが残る",
			RecognitionCues:     []string{"狸", "茶釜", "寺", "見世物"},
			RequiredBeats: []StoryBeat{
				storyBeat("save", "助ける", []string{"助ける", "狸"}, "救う"),
				storyBeat("sell", "茶釜に化けて売られる", []string{"茶釜", "売る"}, "寺", "化ける"),
				storyBeat("escape", "熱さに耐えられず逃げる", []string{"熱い", "逃げる"}, "火", "走る"),
				storyBeat("show", "見世物になる", []string{"見世物", "芸"}, "披露", "人気"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『ぶんぶく茶釜』を、助けた若者と変装の得意な友人が、売りに出された後に逃げ出して路上パフォーマンスで暮らしを立てる話へ置き換える",
				Setting:         "地方寺院と門前の大道芸エリア",
				Viewpoint:       "友人を売りに出してしまった若者の一人称",
				ImmediateChange: "冒頭で、恩人の友人を金のために別の場所へ渡してしまう",
				ConflictShift:   "化ける面白さより、相手を商品にした関係をどう立て直すかが争点になる",
				EndingShape:     "芸は当たっても綱渡りの危うさが残る終わり",
				EndingFlavor:    "救い",
				StoryTitle:      "茶釜の逃走",
				Hook:            "『ぶんぶく茶釜』を、売られた友人と逃げて大道芸を始める話にすると、陽気さの下に危うさが残る。",
				Tone:            "軽快だが不安定さのある語り",
			}},
			"view_shift": {{
				VisibleTwist:    "『ぶんぶく茶釜』を、化ける側の視点から語り、恩返しと商品化の境目を見る",
				Setting:         "寺の台所と夜の路地",
				Viewpoint:       "茶釜に化ける側の一人称",
				ImmediateChange: "最初に、恩返しのつもりで変装したのに売られると知る",
				ConflictShift:   "芸より、誰にどこまで身を預けるかが争点になる",
				EndingShape:     "笑いを取れても、火の熱さを忘れられず終わる",
				EndingFlavor:    "皮肉",
				StoryTitle:      "火にかけられた狸",
				Hook:            "『ぶんぶく茶釜』は、化ける側から見ると恩返しが商品化へ滑る話でもある。",
				Tone:            "ひょうひょうとして少し苦い語り",
			}},
			"value_shift": {{
				VisibleTwist:    "『ぶんぶく茶釜』の見世物を、貧しさを笑いに変えて消費する装置として反転させる",
				Setting:         "SNSで拡散する大道芸文化",
				Viewpoint:       "見世物に立つ側の一人称",
				ImmediateChange: "冒頭で、人気が出るほど自分の危うさも売られていくと分かる",
				ConflictShift:   "暮らしを立てる喜びより、どこまで消費されるかが争点になる",
				EndingShape:     "拍手が増えるほど自由が減る終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "売れる茶釜",
				Hook:            "『ぶんぶく茶釜』の大道芸が、笑いと一緒に危うさまで消費する装置だったら。",
				Tone:            "軽妙だが冷ややかな寓話",
			}},
		},
	},
	"redriding": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"赤い頭巾", "おばあさんへの届け物", "狼の先回り", "おばあさんに化ける", "見抜けない会話", "救出"},
			RoleConstraints:     []string{"届け物を持つ主人公", "先回りする捕食者", "訪問先のおばあさん", "救出に関わる第三者"},
			TabooOrRule:         "道を外れて誘惑に乗らないこと",
			RewardPunishment:    "油断は危機を招き、見抜く力が生還につながる",
			EmotionalAftertaste: "助かっても無垢ではいられない",
			RecognitionCues:     []string{"赤い頭巾", "おばあさん", "狼", "先回り", "化ける"},
			RequiredBeats: []StoryBeat{
				storyBeat("delivery", "届け物の出発", []string{"届け物", "おばあさん", "届け"}, "荷物", "祖母"),
				storyBeat("detour", "道中の足止め", []string{"道草", "引き止め"}, "寄り道", "足止め"),
				storyBeat("overtake", "先回り", []string{"先回り", "待ち伏せ"}, "先に着く"),
				storyBeat("disguise", "変装と誤認", []string{"化ける", "見抜けない"}, "変装", "違和感"),
				storyBeat("rescue", "危機と救出", []string{"救出", "飲み込まれる"}, "閉じ込める", "助け出す"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『赤ずきん』の主人公を夜間配送の担当者に置き換え、届け物の途中でルートを外させる内部誘導の話にする",
				Setting:         "深夜配送が走る住宅街と高齢者施設",
				Viewpoint:       "夜間配送担当として走る主人公の近接三人称",
				ImmediateChange: "冒頭で、主人公は祖母役の入居者へ薬を届けるはずなのに、別ルートへ誘導される",
				ConflictShift:   "狼退治ではなく、先回りと偽装を見抜けるかが核心になる",
				EndingShape:     "助かったあとで、なぜ見抜けなかったかが胸に残る終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "赤ずきん、夜間配送に出る",
				Hook:            "『赤ずきん』を、夜に薬を届ける配送担当の話にすると、先回りの怖さが別の形で立ち上がる。",
				Tone:            "静かな緊張が続く現代サスペンス",
			}},
			"view_shift": {{
				VisibleTwist:    "『赤ずきん』を、おばあさんの視点から語り、先回りされる恐怖と見抜けない会話の時間を伸ばす",
				Setting:         "高齢者住宅と夜の訪問サービス",
				Viewpoint:       "訪問を待つおばあさん役の一人称",
				ImmediateChange: "最初に、いつもの訪問のはずなのに会話の調子だけが少し違うと気づく",
				ConflictShift:   "主人公の成長より、違和感を言葉にできるかが争点になる",
				EndingShape:     "助け出されたあとも、聞き慣れた声を疑う癖だけが残る終わり",
				EndingFlavor:    "喪失",
				StoryTitle:      "おばあさんが聞いた声",
				Hook:            "『赤ずきん』を、おばあさんの耳からたどると、先回りの怖さはずっと静かになる。",
				Tone:            "息をひそめる心理サスペンス",
			}},
			"value_shift": {{
				VisibleTwist:    "『赤ずきん』の届け物を、善意を装った監視と管理の仕組みとして反転させる",
				Setting:         "見守りアプリで行動が可視化された住宅地",
				Viewpoint:       "訪問業務を担う側の一人称",
				ImmediateChange: "冒頭で、親切な訪問のはずが監視の延長でもあると分かる",
				ConflictShift:   "狼の悪意だけでなく、善意の手順が危機を呼ぶことが争点になる",
				EndingShape:     "救出されても、管理の仕組みそのものは残って終わる",
				EndingFlavor:    "皮肉",
				StoryTitle:      "見守られる赤ずきん",
				Hook:            "『赤ずきん』の届け物が、親切と監視の境目に置かれていたら。",
				Tone:            "生活不安を帯びた現代寓話",
			}},
		},
	},
	"cinderella": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"灰まみれ", "舞踏会", "変身", "夜更け", "片方の靴"},
			RoleConstraints:     []string{"虐げられる娘", "彼女を助ける力", "彼女を見いだす王子", "抑圧する家族"},
			TabooOrRule:         "外見や地位だけで他者の価値を決めないこと",
			RewardPunishment:    "押さえ込まれた人が一夜だけ可視化され、最後に選び直される",
			EmotionalAftertaste: "華やかさのあとに長い抑圧の影が残る",
			RecognitionCues:     []string{"灰", "舞踏会", "夜更け", "靴"},
			RequiredBeats: []StoryBeat{
				storyBeat("oppress", "灰まみれの抑圧", []string{"灰", "虐げられる"}, "家事", "継母"),
				storyBeat("ball", "華やかな場へ行く", []string{"舞踏会", "変身"}, "パーティー", "装う"),
				storyBeat("midnight", "夜更けに去る", []string{"夜更け", "去る"}, "零時", "逃げる"),
				storyBeat("shoe", "靴で見つけられる", []string{"靴", "探す"}, "片方", "見つける"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『シンデレラ』を、雑務ばかり押しつけられる契約社員が一夜限りの業界イベントで可視化され、残した靴で身元を追われる話へ置き換える",
				Setting:         "ホテル宴会場と古い社宅",
				Viewpoint:       "裏方として働く契約社員の一人称",
				ImmediateChange: "冒頭で、灰のような雑務に埋もれる日常がまず示される",
				ConflictShift:   "恋愛だけでなく、一夜の可視化を自分の人生に変えられるかが争点になる",
				EndingShape:     "華やかな一夜のあと、靴だけが現実をつなぐ終わり",
				EndingFlavor:    "救い",
				StoryTitle:      "片方のパンプス",
				Hook:            "『シンデレラ』を、一夜限りの業界イベントで見いだされる契約社員の話にすると、靴の意味が少し現実的になる。",
				Tone:            "華やかさと切実さのある語り",
			}},
			"view_shift": {{
				VisibleTwist:    "『シンデレラ』を、裏方で彼女を整えた側の視点から語り、一夜の変身がどれだけ切実だったかを描く",
				Setting:         "バックヤードと宴会場の往復",
				Viewpoint:       "身支度を手伝った同僚の一人称",
				ImmediateChange: "最初に、彼女の一夜が夢ではなく必要だったと語る",
				ConflictShift:   "見いだされる瞬間より、その一夜を成立させる周囲の手つきが争点になる",
				EndingShape:     "靴だけを残して消えた背中を見送る終わり",
				EndingFlavor:    "救い",
				StoryTitle:      "灰の外側を知る者",
				Hook:            "『シンデレラ』は、着替えを手伝った側から見ると切実な脱走劇でもある。",
				Tone:            "親密であたたかな語り",
			}},
			"value_shift": {{
				VisibleTwist:    "『シンデレラ』の変身を、評価される見た目だけが一夜だけ与えられる制度の暴力として反転させる",
				Setting:         "容姿と肩書きが評価されるイベント産業",
				Viewpoint:       "変身させられる本人の一人称",
				ImmediateChange: "冒頭で、変身は自由ではなく一時的な通行証だと分かる",
				ConflictShift:   "王子に見つかることより、見た目が剥がれたあとにも自分が残るかが争点になる",
				EndingShape:     "靴だけが証拠になり、素顔はまた評価の外へ戻される終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "零時の通行証",
				Hook:            "『シンデレラ』の変身が、一夜だけ発行される通行証にすぎなかったら。",
				Tone:            "華やかな場に冷たさが差す寓話",
			}},
		},
	},
	"snowwhite": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"嫉妬", "追放", "毒りんご", "七人の小人", "ガラスの棺", "再生"},
			RoleConstraints:     []string{"嫉妬される主役", "執着する対立役", "匿う共同体", "再生を見届ける証人"},
			TabooOrRule:         "嫉妬に従って他者を排除しないこと",
			RewardPunishment:    "執着は孤立へ向かい、連帯は再生を呼ぶ",
			EmotionalAftertaste: "救われても傷は残る",
			RecognitionCues:     []string{"毒りんご", "小人", "棺", "嫉妬"},
			RequiredBeats: []StoryBeat{
				storyBeat("envy", "嫉妬と追放", []string{"嫉妬", "追放"}, "排除", "逃亡"),
				storyBeat("shelter", "匿われる", []string{"小人", "匿う"}, "共同体", "保護"),
				storyBeat("poison", "毒の贈り物", []string{"毒りんご", "毒"}, "甘い罠"),
				storyBeat("sleep", "仮死と再生", []string{"棺", "目を覚ます"}, "眠る", "再生"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『白雪姫』を、目立つ若い職員が嫉妬で組織から外され、少人数の共同体に匿われたあと、甘い贈り物で一度止められる話へ置き換える",
				Setting:         "華やかなブランド企業と郊外の共同工房",
				Viewpoint:       "排除された若手職員の近接三人称",
				ImmediateChange: "冒頭で、嫉妬が制度的な追放に変わる",
				ConflictShift:   "王子との再会より、共同体に守られながら自分を取り戻せるかが争点になる",
				EndingShape:     "再生しても、嫉妬の傷が消えない終わり",
				EndingFlavor:    "救い",
				StoryTitle:      "りんごの止まる夜",
				Hook:            "『白雪姫』を、嫉妬で外された若手職員と小さな共同体の話にすると、再生の重みが増す。",
				Tone:            "華やかさの裏に痛みが残る語り",
			}},
			"view_shift": {{
				VisibleTwist:    "『白雪姫』を、匿った共同体の一人の視点から語り、守ることの限界と再生の瞬間を見つめる",
				Setting:         "共同工房の寮",
				Viewpoint:       "白雪姫を匿った側の一人称",
				ImmediateChange: "最初に、守りきれると思っていた自信が揺らぐ",
				ConflictShift:   "王妃の悪意より、共同体が他者を守る責任の重さが争点になる",
				EndingShape:     "息を吹き返しても、守れなかった一瞬が残る終わり",
				EndingFlavor:    "喪失",
				StoryTitle:      "小人の見た棺",
				Hook:            "『白雪姫』は、匿った側から見ると守る責任の話でもある。",
				Tone:            "丁寧で痛みのある回想",
			}},
			"value_shift": {{
				VisibleTwist:    "『白雪姫』の美しさを、比較と評価の市場で消費される資源として反転させる",
				Setting:         "容姿と好感度が数値化される芸能業界",
				Viewpoint:       "評価される側の一人称",
				ImmediateChange: "冒頭で、褒められるほど追い詰められる構造が見える",
				ConflictShift:   "嫉妬する個人より、比較を生む仕組みそのものが争点になる",
				EndingShape:     "息を吹き返しても、また数値化の場に戻される終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "ガラスの評価表",
				Hook:            "『白雪姫』の鏡が、好感度の数値を返す市場だったら。",
				Tone:            "きらびやかで冷たい寓話",
			}},
		},
	},
	"hansel": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"森に置き去り", "兄妹", "お菓子の家", "魔女", "かまど", "帰還"},
			RoleConstraints:     []string{"置き去りにされる兄妹", "食べ物で誘う対立役", "閉じ込められる兄", "機転で逆転する妹"},
			TabooOrRule:         "飢えと不安につけ込む誘いを無邪気に信じないこと",
			RewardPunishment:    "見捨てられた兄妹は機転で戻り、食べようとした側は火で終わる",
			EmotionalAftertaste: "助かっても、置き去りの記憶は残る",
			RecognitionCues:     []string{"森", "兄妹", "お菓子の家", "魔女", "かまど"},
			RequiredBeats: []StoryBeat{
				storyBeat("abandon", "置き去り", []string{"森", "置き去り"}, "捨てる"),
				storyBeat("tempt", "甘い家の誘惑", []string{"お菓子の家", "甘い"}, "家", "誘う"),
				storyBeat("cage", "閉じ込められる", []string{"檻", "閉じ込める"}, "捕まる"),
				storyBeat("oven", "かまどで逆転し帰る", []string{"かまど", "帰る"}, "火", "戻る"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『ヘンゼルとグレーテル』を、生活苦で放り出された兄妹が、無料支援を装う施設に誘い込まれ、最後は設備を逆用して逃げる話へ置き換える",
				Setting:         "郊外の空き地と怪しい福祉施設",
				Viewpoint:       "妹の近接一人称",
				ImmediateChange: "冒頭で、兄妹は生活苦の中で本当に置き去りにされる",
				ConflictShift:   "冒険より、甘い救済の顔をした搾取を見抜けるかが争点になる",
				EndingShape:     "逃げ切っても、置き去りの痛みが消えない終わり",
				EndingFlavor:    "救い",
				StoryTitle:      "甘い家の出口",
				Hook:            "『ヘンゼルとグレーテル』を、支援を装う施設から兄妹が抜け出す話にすると、甘さが急に怖くなる。",
				Tone:            "張り詰めた兄妹サスペンス",
			}},
			"view_shift": {{
				VisibleTwist:    "『ヘンゼルとグレーテル』を、妹の視点に固定し、兄を助けるために怖さを後回しにする決断を描く",
				Setting:         "誘い込まれた施設の内部",
				Viewpoint:       "妹の一人称",
				ImmediateChange: "最初に、泣くより考えるほうを選んだと明かす",
				ConflictShift:   "魔女退治より、誰かの保護を待たずに兄を取り返せるかが争点になる",
				EndingShape:     "帰れたあとで初めて震えが来る終わり",
				EndingFlavor:    "救い",
				StoryTitle:      "グレーテルのかまど",
				Hook:            "『ヘンゼルとグレーテル』を妹の視点だけでたどると、怖さより判断の速さが前に出る。",
				Tone:            "緊迫した近接一人称",
			}},
			"value_shift": {{
				VisibleTwist:    "『ヘンゼルとグレーテル』の甘い家を、支援と引き換えに依存を作る仕組みとして反転させる",
				Setting:         "無料提供と広告が絡む民間支援網",
				Viewpoint:       "支援を受ける側の一人称",
				ImmediateChange: "冒頭で、無料の甘さが出口のない契約でもあると分かる",
				ConflictShift:   "生き延びること以上に、依存を断って帰れるかが争点になる",
				EndingShape:     "逃げても、次の飢えがまた同じ甘さを呼ぶ終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "無料の家",
				Hook:            "『ヘンゼルとグレーテル』のお菓子の家が、依存を作る支援装置だったら。",
				Tone:            "冷たい社会寓話",
			}},
		},
	},
	"bremen": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"年老いた動物", "音楽隊の旅", "盗賊の家", "力を合わせて追い払う", "そこに住む"},
			RoleConstraints:     []string{"捨てられた動物たち", "旅を提案する主役", "盗賊", "新しい住まい"},
			TabooOrRule:         "役に立たないと切り捨てられても、自分の声を失わないこと",
			RewardPunishment:    "行き場のない者同士が声を重ねると住まいを得る",
			EmotionalAftertaste: "目的地より一緒にいる居場所が残る",
			RecognitionCues:     []string{"ロバ", "犬", "猫", "雄鶏", "音楽隊", "盗賊"},
			RequiredBeats: []StoryBeat{
				storyBeat("gather", "年老いた仲間が集まる", []string{"ロバ", "犬", "猫", "雄鶏"}, "集まる"),
				storyBeat("journey", "音楽隊を目指す旅", []string{"音楽隊", "旅"}, "ブレーメン", "進む"),
				storyBeat("thieves", "盗賊の家を見つける", []string{"盗賊", "家"}, "見つける"),
				storyBeat("home", "声を重ねて追い払い住む", []string{"追い払う", "住む"}, "大声", "新居"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『ブレーメンの音楽隊』を、役立たず扱いされた年配の四人が廃業寸前のライブバーを目指し、先にいた不法占拠者を追い出して住みつく話へ置き換える",
				Setting:         "郊外の国道沿いと潰れかけたライブバー",
				Viewpoint:       "最初に旅を言い出した年配ロバ役の一人称",
				ImmediateChange: "冒頭で、もう使えないと切り捨てられた者たちが集まる",
				ConflictShift:   "成功より、一緒に声を出せる居場所を持てるかが争点になる",
				EndingShape:     "目的地に着かなくても、居場所が見つかる終わり",
				EndingFlavor:    "救い",
				StoryTitle:      "国道沿いの音楽隊",
				Hook:            "『ブレーメンの音楽隊』を、切り捨てられた年配者たちの再起の旅に置き換えると、目的地より居場所が光る。",
				Tone:            "朗らかな再起譚",
			}},
			"view_shift": {{
				VisibleTwist:    "『ブレーメンの音楽隊』を、最後に加わった仲間の視点から語り、追いつく側の不安と安堵を描く",
				Setting:         "旅の後ろから追う一本道",
				Viewpoint:       "最後に加わる雄鶏役の一人称",
				ImmediateChange: "最初に、置いていかれる恐怖から話し始める",
				ConflictShift:   "盗賊退治より、仲間に入れてもらえるかが争点になる",
				EndingShape:     "大声を出した瞬間に居場所ができる終わり",
				EndingFlavor:    "救い",
				StoryTitle:      "最後に鳴いた者",
				Hook:            "『ブレーメンの音楽隊』は、最後に追いついた者の目にはもっと切実な旅だった。",
				Tone:            "親しみのある一人称",
			}},
			"value_shift": {{
				VisibleTwist:    "『ブレーメンの音楽隊』の仲間集めを、不要品同士の連帯ではなく再就職市場からこぼれた者の相互扶助として反転させる",
				Setting:         "非正規雇用と空き物件が多い地方都市",
				Viewpoint:       "職を失った一人称",
				ImmediateChange: "冒頭で、役立たないと切られた人材の寄せ集めだと分かる",
				ConflictShift:   "夢の音楽隊より、最低限住める場所をどう奪い返すかが争点になる",
				EndingShape:     "成功ではなく共同生活の始まりで終わる",
				EndingFlavor:    "救い",
				StoryTitle:      "住みついた音楽隊",
				Hook:            "『ブレーメンの音楽隊』の旅が、再就職市場からこぼれた者の相互扶助だったら。",
				Tone:            "現代的だが温かい群像劇",
			}},
		},
	},
	"puss": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"長靴の猫", "主人を侯爵に仕立てる", "贈り物の演出", "人食い鬼をだます", "城を得る"},
			RoleConstraints:     []string{"機転のきく猫", "身分のない主人", "権力者", "だまされる怪物"},
			TabooOrRule:         "身分の虚飾に飲まれて、自分が誰のために働くかを見失わないこと",
			RewardPunishment:    "機転は主人を押し上げ、傲慢な支配者は自分の変身に負ける",
			EmotionalAftertaste: "爽快さの裏に芝居の危うさが残る",
			RecognitionCues:     []string{"猫", "長靴", "侯爵", "鬼", "城"},
			RequiredBeats: []StoryBeat{
				storyBeat("equip", "猫が装う", []string{"猫", "長靴"}, "身支度", "袋"),
				storyBeat("stage", "主人を侯爵に仕立てる", []string{"侯爵", "仕立てる"}, "贈り物", "演出"),
				storyBeat("monster", "怪物をだます", []string{"鬼", "だます"}, "変身", "食う"),
				storyBeat("castle", "城を得る", []string{"城", "得る"}, "館", "手に入れる"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『長靴をはいた猫』を、口の立つ敏腕秘書が無名の若者を侯爵のように演出し、最後に強権的なオーナーを出し抜く話へ置き換える",
				Setting:         "高級ホテル街と老舗企業の本社",
				Viewpoint:       "猫役の秘書の一人称",
				ImmediateChange: "冒頭で、装いひとつで相手の見え方を変えてしまう",
				ConflictShift:   "冒険より、芝居を最後まで破綻させずに権力者を出し抜けるかが争点になる",
				EndingShape:     "勝っても全部が演出だった危うさが残る終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "長靴の秘書",
				Hook:            "『長靴をはいた猫』を、敏腕秘書が無名の若者を仕立て上げる話にすると、機転がほとんど詐術に見えてくる。",
				Tone:            "軽快で狡猾な語り",
			}},
			"view_shift": {{
				VisibleTwist:    "『長靴をはいた猫』を、仕立て上げられる主人の視点から語り、成功が自分のものか分からない不安を描く",
				Setting:         "急に豪華になる生活圏",
				Viewpoint:       "侯爵に見せられる側の一人称",
				ImmediateChange: "最初に、何もしていないのに肩書きだけが増えていく怖さを明かす",
				ConflictShift:   "出世の快感より、他人の芝居に乗るしかない不安が争点になる",
				EndingShape:     "城を手に入れても、自分の足で取った実感が薄い終わり",
				EndingFlavor:    "喪失",
				StoryTitle:      "侯爵にされた男",
				Hook:            "『長靴をはいた猫』は、仕立て上げられる側から見ると成功が他人の手つきでできていく話だ。",
				Tone:            "少し戸惑いのある一人称",
			}},
			"value_shift": {{
				VisibleTwist:    "『長靴をはいた猫』の機転を、実力より演出が勝つ評価市場として反転させる",
				Setting:         "ブランド戦略とイメージ管理が支配する業界",
				Viewpoint:       "演出する側の一人称",
				ImmediateChange: "冒頭で、中身より肩書きが先に信用を生むと分かる",
				ConflictShift:   "怪物退治より、演出だけで人を動かす危うさが争点になる",
				EndingShape:     "勝ち残っても、次の演出がないと崩れる終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "侯爵ブランド",
				Hook:            "『長靴をはいた猫』の成功が、実力ではなくブランド演出の勝利だったら。",
				Tone:            "華やかで冷たい産業寓話",
			}},
		},
	},
	"threepigs": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"藁の家", "木の家", "れんがの家", "狼が吹き飛ばす", "煙突"},
			RoleConstraints:     []string{"三匹の子ぶた", "襲う狼", "家の強度の差", "最後に耐える家"},
			TabooOrRule:         "楽をして備えを怠らないこと",
			RewardPunishment:    "手間を惜しまない備えだけが最後に残る",
			EmotionalAftertaste: "単純な教訓の裏に、失った家の軽さが残る",
			RecognitionCues:     []string{"藁", "木", "れんが", "狼", "煙突"},
			RequiredBeats: []StoryBeat{
				storyBeat("build", "家を建てる", []string{"藁", "木", "れんが"}, "家"),
				storyBeat("blow", "狼が吹き飛ばす", []string{"狼", "吹き飛ばす"}, "壊す"),
				storyBeat("gather", "最後の家へ逃げ込む", []string{"逃げる", "れんが"}, "集まる"),
				storyBeat("chimney", "煙突で逆転する", []string{"煙突"}, "熱湯", "逆転"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『三匹の子ぶた』を、三人の若手が別々の低予算住居を選び、最後に最も手間をかけた住まいだけが悪質な立ち退き圧力に耐える話へ置き換える",
				Setting:         "郊外の賃貸住宅地",
				Viewpoint:       "最後に堅い家を選んだ一人称",
				ImmediateChange: "冒頭で、三人が住居コストの違う選択をする",
				ConflictShift:   "狼との戦いより、備えの差が生活防衛になるかが争点になる",
				EndingShape:     "残った家の堅さと、失った二つの家の軽さが同時に残る終わり",
				EndingFlavor:    "救い",
				StoryTitle:      "れんがの部屋",
				Hook:            "『三匹の子ぶた』を、住宅選びと立ち退き圧力の話にすると、備えの差が急に生々しくなる。",
				Tone:            "分かりやすく張りのある現代寓話",
			}},
			"view_shift": {{
				VisibleTwist:    "『三匹の子ぶた』を、最初に家を失う側の視点から語り、軽さの代償を後から噛みしめる話にする",
				Setting:         "安い住居からの転々とした避難",
				Viewpoint:       "最初に家を失う側の一人称",
				ImmediateChange: "最初に、早く楽をしたかったと認める",
				ConflictShift:   "狼より、自分の選択の浅さをどう受け止めるかが争点になる",
				EndingShape:     "兄弟の堅い家に助けられて終わる",
				EndingFlavor:    "救い",
				StoryTitle:      "藁の家を出た日",
				Hook:            "『三匹の子ぶた』は、最初に失う側から見ると準備不足の記録でもある。",
				Tone:            "素直な反省の混じる語り",
			}},
			"value_shift": {{
				VisibleTwist:    "『三匹の子ぶた』の教訓を、自己責任だけを強いる住宅格差の話として反転させる",
				Setting:         "住居コストが極端に違う都市周縁部",
				Viewpoint:       "備えたくても備えられない側の一人称",
				ImmediateChange: "冒頭で、手を抜いたのではなく選択肢が少なかったと分かる",
				ConflictShift:   "努力の差だけで片づけられるかが争点になる",
				EndingShape:     "れんがの家だけが残っても、格差はそのまま終わる",
				EndingFlavor:    "皮肉",
				StoryTitle:      "残る家、残らない家",
				Hook:            "『三匹の子ぶた』の家づくりが、自己責任だけでは片づかない住宅格差の話だったら。",
				Tone:            "教訓をねじる社会寓話",
			}},
		},
	},
	"beauty": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"父の代わり", "野獣の城", "毎夜の求婚", "心を見る", "呪いが解ける"},
			RoleConstraints:     []string{"身代わりになる娘", "野獣", "家族", "呪いを解く愛情"},
			TabooOrRule:         "外見や恐怖だけで相手を切り捨てないこと",
			RewardPunishment:    "恐れを超えて向き合うことで呪いが解ける",
			EmotionalAftertaste: "受け入れた相手の傷も一緒に引き受ける感触が残る",
			RecognitionCues:     []string{"野獣", "城", "求婚", "呪い"},
			RequiredBeats: []StoryBeat{
				storyBeat("substitute", "父の代わりに行く", []string{"父", "代わり"}, "身代わり"),
				storyBeat("castle", "野獣の城で暮らす", []string{"野獣", "城"}, "屋敷"),
				storyBeat("proposal", "毎夜の求婚", []string{"求婚", "毎夜"}, "結婚してくれ"),
				storyBeat("release", "受け入れて呪いが解ける", []string{"呪い", "解ける"}, "心を見る", "戻る"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『美女と野獣』を、家族の借金の代わりに孤立した経営者の屋敷へ入る若い女性が、恐ろしい外見ではなく噂に覆われた相手と暮らす話へ置き換える",
				Setting:         "閉鎖的な郊外の豪邸",
				Viewpoint:       "身代わりで入る若い女性の一人称",
				ImmediateChange: "冒頭で、父の代わりに危険な契約を引き受ける",
				ConflictShift:   "恋愛成就より、恐れの噂に塗れた相手の輪郭を見直せるかが争点になる",
				EndingShape:     "呪いが解けても、相手の傷を引き受ける実感が残る終わり",
				EndingFlavor:    "救い",
				StoryTitle:      "野獣の屋敷で",
				Hook:            "『美女と野獣』を、家族の負債の肩代わりで閉ざされた屋敷に入る話にすると、心を見る行為がもっと現実的になる。",
				Tone:            "静かな緊張と親密さの語り",
			}},
			"view_shift": {{
				VisibleTwist:    "『美女と野獣』を、野獣側の視点から語り、毎夜の求婚が拒絶と希望の繰り返しだったことを見せる",
				Setting:         "広すぎる屋敷の内部",
				Viewpoint:       "野獣の一人称",
				ImmediateChange: "最初に、怖がらせないよう距離を測り続けていると明かす",
				ConflictShift:   "娘の成長より、拒絶されても暴れずに待てるかが争点になる",
				EndingShape:     "受け入れられる瞬間より、その前の長い夜が残る終わり",
				EndingFlavor:    "救い",
				StoryTitle:      "野獣の夜ごとの声",
				Hook:            "『美女と野獣』は、野獣の側から見ると断られ続ける夜の物語でもある。",
				Tone:            "抑えた感情のある一人称",
			}},
			"value_shift": {{
				VisibleTwist:    "『美女と野獣』の受容を、危険な相手を女性が癒やすべきだという圧力として反転させる",
				Setting:         "ケア役割が女性に偏る保守的な共同体",
				Viewpoint:       "期待される側の一人称",
				ImmediateChange: "冒頭で、優しさを求められること自体が負担だと分かる",
				ConflictShift:   "愛の奇跡より、誰が誰を救う責任を負わされるかが争点になる",
				EndingShape:     "呪いは解けても、ケアの負荷だけが残る終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "野獣を癒やす役",
				Hook:            "『美女と野獣』の奇跡が、女性にケアを押しつける物語だったらどう見えるか。",
				Tone:            "柔らかく刺す現代寓話",
			}},
		},
	},
	"aladdin": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"洞窟でだまされる", "魔法のランプ", "魔人", "王女との結婚", "ランプを奪われる", "機転で奪還する"},
			RoleConstraints:     []string{"だまされる若者", "命令に従う魔人", "力を奪う魔法使い", "奇跡を受け取る王女"},
			TabooOrRule:         "力を得ても、それを他者支配の道具にしないこと",
			RewardPunishment:    "願いで得たものは、奪われたときに本当の価値を問われる",
			EmotionalAftertaste: "まぶしい成功の裏に、使われる側の息苦しさが残る",
			RecognitionCues:     []string{"ランプ", "魔人", "魔法使い", "王女"},
			RequiredBeats: []StoryBeat{
				storyBeat("trick", "だまされて力に触れる", []string{"だまされる", "洞窟"}, "誘い込まれる"),
				storyBeat("gain", "ランプと魔人を得る", []string{"ランプ", "魔人"}, "願いの力"),
				storyBeat("loss", "力を奪われる", []string{"奪われる", "失う"}, "横取り"),
				storyBeat("recover", "機転で奪還する", []string{"奪還", "取り戻す"}, "出し抜く"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『アラジンと魔法のランプ』を、裏口採用の若者が怪しい案件にだまされて権限トークンを手にし、一度奪われた立場を機転で取り戻す話に置き換える",
				Setting:         "高層複合ビルと地下保守区画",
				Viewpoint:       "だまされる若者の一人称",
				ImmediateChange: "冒頭で、怪しい依頼人に導かれて閉ざされた区画へ入る",
				ConflictShift:   "願望成就より、力を持ったあと誰に使われるかが争点になる",
				EndingShape:     "取り戻しても、使われる側の息苦しさが残る終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "ランプ権限の夜",
				Hook:            "『アラジンと魔法のランプ』を、裏口採用の若者が権限トークンを巡ってだまされる話にすると、願いより支配が前に出る。",
				Tone:            "まばゆさの裏に圧のある現代奇譚",
			}},
			"view_shift": {{
				VisibleTwist:    "『アラジンと魔法のランプ』を、願いをかなえる力に使われ続けた魔人の視点から語り直す",
				Setting:         "豪奢な宮殿の裏側と、命令だけが飛び交う控えの空間",
				Viewpoint:       "ランプから呼び出される魔人の一人称",
				ImmediateChange: "冒頭から、主人を助ける魔法ではなく、命令され続ける息苦しさで始める",
				ConflictShift:   "冒険の達成より、誰の願いに従うべきかが核心になる",
				EndingShape:     "救ったはずの相手から、最後に距離を取る終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "ランプの内側のアラジン",
				Hook:            "『アラジンと魔法のランプ』を、願いをかなえる側が見ていたら、救いはもっと息苦しく見える。",
				Tone:            "従属と反発がにじむ内省的な語り",
			}},
			"value_shift": {{
				VisibleTwist:    "『アラジンと魔法のランプ』の願いを、成功と引き換えに依存関係を深める権限の貸与として反転させる",
				Setting:         "巨大権限を一時貸与する企業統治の世界",
				Viewpoint:       "権限を手にした若者の一人称",
				ImmediateChange: "冒頭で、願いがかなうたびに返せない借りが増えると分かる",
				ConflictShift:   "出世の快感より、その力が自分のものではないことが争点になる",
				EndingShape:     "奪い返しても、借りた力で築いたものの薄さが残る終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "借りもののランプ",
				Hook:            "『アラジンと魔法のランプ』の願いが、返せない借りを増やす権限貸与だったら。",
				Tone:            "きらびやかで苦い現代寓話",
			}},
		},
	},
	"ali40": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"開けゴマ", "宝の洞窟", "兄の欲", "モルジアナの知恵", "盗賊の頭領"},
			RoleConstraints:     []string{"偶然秘密を知る木こり", "欲を出す兄", "知恵のある召使い", "盗賊たち"},
			TabooOrRule:         "秘密の富を欲で独占しようとしないこと",
			RewardPunishment:    "秘密を知っただけでは足りず、最後は知恵が命を救う",
			EmotionalAftertaste: "幸運より、支えた知恵のほうが印象に残る",
			RecognitionCues:     []string{"開けゴマ", "洞窟", "盗賊", "モルジアナ"},
			RequiredBeats: []StoryBeat{
				storyBeat("discover", "秘密の入口を知る", []string{"開けゴマ", "洞窟"}, "秘密の入口"),
				storyBeat("greed", "兄が欲を出す", []string{"兄", "欲"}, "独占"),
				storyBeat("threat", "盗賊が家を突き止める", []string{"盗賊", "家"}, "頭領", "狙う"),
				storyBeat("wit", "知恵で守る", []string{"モルジアナ", "知恵"}, "助ける", "退ける"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『アリババと四十人の盗賊』を、偶然内部保管庫の合言葉を知った小さな業者が、兄の欲と有能なスタッフの機転で命運を分ける話へ置き換える",
				Setting:         "倉庫街の秘密保管庫と町工場",
				Viewpoint:       "秘密を知る業者の一人称",
				ImmediateChange: "冒頭で、偶然聞いた合言葉が人生を変える",
				ConflictShift:   "宝探しより、知ってしまった秘密を誰とどう扱うかが争点になる",
				EndingShape:     "富より、最後に守った知恵の持ち主が残る終わり",
				EndingFlavor:    "救い",
				StoryTitle:      "開けゴマの倉庫",
				Hook:            "『アリババと四十人の盗賊』を、秘密保管庫の合言葉を知った小業者の話にすると、幸運より知恵が前に出る。",
				Tone:            "機転の効いた現代活劇",
			}},
			"view_shift": {{
				VisibleTwist:    "『アリババと四十人の盗賊』を、家を守った賢い使用人の視点から語り、主人の幸運を実務で支える側を描く",
				Setting:         "狙われる家の台所と裏口",
				Viewpoint:       "モルジアナ役の一人称",
				ImmediateChange: "最初に、主人の幸運より後始末の多さを嘆く",
				ConflictShift:   "英雄譚より、家を守る実務知が争点になる",
				EndingShape:     "主役が称賛されても、守った側の手つきが忘れられない終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "モルジアナの裏口",
				Hook:            "『アリババと四十人の盗賊』は、家を守った側から見ると幸運より実務の連続だった。",
				Tone:            "機敏で少し辛口な語り",
			}},
			"value_shift": {{
				VisibleTwist:    "『アリババと四十人の盗賊』の秘密の富を、見つけた瞬間から共同体を壊す情報格差として反転させる",
				Setting:         "流通情報が富になる半地下経済",
				Viewpoint:       "秘密を知った本人の一人称",
				ImmediateChange: "冒頭で、富より秘密そのものが重荷になると分かる",
				ConflictShift:   "盗賊との戦いより、情報格差が家族を壊すことが争点になる",
				EndingShape:     "財産は残っても、元の単純な暮らしは戻らない終わり",
				EndingFlavor:    "喪失",
				StoryTitle:      "合言葉の代償",
				Hook:            "『アリババと四十人の盗賊』の富が、知った者から共同体を壊す情報そのものだったら。",
				Tone:            "少し重たい情報寓話",
			}},
		},
	},
	"emperors": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"見えない服", "誰も真実を言えない", "行進", "子どもの一言"},
			RoleConstraints:     []string{"虚飾の王", "詐欺師", "黙る大人たち", "真実を言う子ども"},
			TabooOrRule:         "愚かに見られたくない恐れで真実を黙らないこと",
			RewardPunishment:    "集団の沈黙は滑稽を拡大し、一言の真実がそれを壊す",
			EmotionalAftertaste: "笑いのあとに沈黙の怖さが残る",
			RecognitionCues:     []string{"服", "裸", "王様", "子ども"},
			RequiredBeats: []StoryBeat{
				storyBeat("con", "見えないものを売り込む", []string{"服", "見えない"}, "布", "詐欺"),
				storyBeat("silence", "誰も言えない", []string{"言えない", "黙る"}, "愚か", "沈黙"),
				storyBeat("parade", "行進する", []string{"行進", "王様"}, "公の場", "披露"),
				storyBeat("speak", "子どもが言う", []string{"子ども", "裸"}, "本当", "叫ぶ"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『裸の王様』を、見えない成果物を信じ込んだトップが社内イベントで披露し、最後に若い見学者の一言で空気が変わる話へ置き換える",
				Setting:         "虚飾の強い大企業の発表会",
				Viewpoint:       "発表会を支える末端スタッフの一人称",
				ImmediateChange: "冒頭で、誰も中身を見ていない企画が進んでいると分かる",
				ConflictShift:   "王の滑稽さより、全員が口をつぐむ構造が争点になる",
				EndingShape:     "一言で壊れても、沈黙していた時間が消えない終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "見えない企画書",
				Hook:            "『裸の王様』を、見えない成果物を信じ込んだ発表会の話にすると、沈黙の怖さがそのまま出る。",
				Tone:            "滑稽さと怖さが同居する語り",
			}},
			"view_shift": {{
				VisibleTwist:    "『裸の王様』を、最後に真実を口にした子ども側の視点から語り、周囲の大人の顔色の異様さを描く",
				Setting:         "公開イベントの観覧席",
				Viewpoint:       "見学に来た子どもの一人称",
				ImmediateChange: "最初に、みんなが変なものを褒めている違和感から始める",
				ConflictShift:   "王の失態より、なぜ誰も言わないのかが争点になる",
				EndingShape:     "言ったあとで初めて大人の沈黙の重さに気づく終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "言ってしまった子ども",
				Hook:            "『裸の王様』は、最後に口を開いた子どもの目には大人たちの沈黙の話だった。",
				Tone:            "素直で鋭い一人称",
			}},
			"value_shift": {{
				VisibleTwist:    "『裸の王様』の服を、理解しているふりをしないと排除される専門性のシグナルとして反転させる",
				Setting:         "専門用語が権威になる組織文化",
				Viewpoint:       "分かったふりをしていた社員の一人称",
				ImmediateChange: "冒頭で、知らないと言えない空気が可視化される",
				ConflictShift:   "詐欺師だけでなく、同調圧力そのものが争点になる",
				EndingShape:     "真実が出ても、また別の見えない服が作られそうで終わる",
				EndingFlavor:    "皮肉",
				StoryTitle:      "分かったふりの服",
				Hook:            "『裸の王様』の服が、理解しているふりをしないと排除される印だったら。",
				Tone:            "現代的で刺すような寓話",
			}},
		},
	},
	"matchgirl": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"大みそか", "マッチ", "幻", "祖母", "凍えて死ぬ"},
			RoleConstraints:     []string{"寒さの中の少女", "買わない町", "幻として現れる温もり", "迎える祖母"},
			TabooOrRule:         "貧しさを見えないものとして扱わないこと",
			RewardPunishment:    "現実では救われず、最後に幻だけが抱きしめる",
			EmotionalAftertaste: "美しさより寒さの残酷さが残る",
			RecognitionCues:     []string{"マッチ", "大みそか", "祖母", "幻"},
			RequiredBeats: []StoryBeat{
				storyBeat("cold", "寒さの中で売る", []string{"大みそか", "マッチ"}, "寒い", "売る"),
				storyBeat("vision", "幻を見る", []string{"幻", "暖炉"}, "ごちそう", "ツリー"),
				storyBeat("grandmother", "祖母が現れる", []string{"祖母"}, "抱く"),
				storyBeat("death", "静かに死ぬ", []string{"死ぬ", "凍える"}, "息を引き取る"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『マッチ売りの少女』を、大みそかの繁華街で充電器や小物を売る少女が、スクリーン越しの暖かさだけを見ながら朝を迎える話へ置き換える",
				Setting:         "年末の繁華街とビルの谷間",
				Viewpoint:       "寒さの中で売り歩く少女の近接三人称",
				ImmediateChange: "冒頭で、誰も足を止めない年越しの街が示される",
				ConflictShift:   "救済より、現実の寒さに対して幻しか持てないことが争点になる",
				EndingShape:     "美しい映像のあとに冷えた朝だけが残る終わり",
				EndingFlavor:    "喪失",
				StoryTitle:      "年の瀬の灯り",
				Hook:            "『マッチ売りの少女』を、年末の繁華街で小物を売る少女の話にすると、街の明るさがそのまま残酷になる。",
				Tone:            "静かで痛ましい語り",
			}},
			"view_shift": {{
				VisibleTwist:    "『マッチ売りの少女』を、見かけながら通り過ぎた大人の視点から語り、見ないふりの罪を残す",
				Setting:         "帰省客で混む駅前通り",
				Viewpoint:       "通り過ぎた会社員の一人称",
				ImmediateChange: "最初に、見たのに見なかったと認める",
				ConflictShift:   "少女の幻より、見て見ぬふりの鈍さが争点になる",
				EndingShape:     "翌朝のニュースで遅すぎる後悔が残る終わり",
				EndingFlavor:    "喪失",
				StoryTitle:      "通り過ぎた人",
				Hook:            "『マッチ売りの少女』は、通り過ぎた側から見ると見ないふりの記録になる。",
				Tone:            "罪悪感の強い一人称",
			}},
			"value_shift": {{
				VisibleTwist:    "『マッチ売りの少女』の幻を、貧困を飾って消費する都市の美談装置として反転させる",
				Setting:         "慈善キャンペーンが並ぶ年末都市",
				Viewpoint:       "写真に撮られる側の一人称",
				ImmediateChange: "冒頭で、苦しさより絵になることが優先されていると分かる",
				ConflictShift:   "少女個人の悲劇より、貧困を美談に変える仕組みが争点になる",
				EndingShape:     "温かなハッシュタグだけが残る終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "映えるマッチ",
				Hook:            "『マッチ売りの少女』の灯りが、貧しさを美談に変える都市の装置だったら。",
				Tone:            "美しさを拒む社会寓話",
			}},
		},
	},
	"littlemermaid": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"王子を助ける", "声と引き換えに足", "魔女", "別の姫と結婚", "泡になる"},
			RoleConstraints:     []string{"人魚姫", "王子", "代償を取る魔女", "誤認される別の姫"},
			TabooOrRule:         "愛のために自分の声を差し出しすぎないこと",
			RewardPunishment:    "願いはかなわず、痛みと引き換えに魂だけが上へ向かう",
			EmotionalAftertaste: "報われなさの透明さが残る",
			RecognitionCues:     []string{"人魚", "声", "足", "王子", "泡"},
			RequiredBeats: []StoryBeat{
				storyBeat("rescue", "王子を助ける", []string{"助ける", "王子"}, "救う"),
				storyBeat("trade", "声と足を引き換える", []string{"声", "足"}, "引き換え", "魔女"),
				storyBeat("marry", "別の姫と結婚する", []string{"結婚", "別の姫"}, "選ばれない"),
				storyBeat("foam", "泡になる", []string{"泡"}, "消える", "空へ"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『人魚姫』を、命を救った相手に近づくために自分の発言権を捨てた若い女性が、最後に何も告げられないまま消えていく話へ置き換える",
				Setting:         "港町と高級ホテル街",
				Viewpoint:       "声を失う若い女性の一人称",
				ImmediateChange: "冒頭で、救った相手に近づくために自分の声を差し出してしまう",
				ConflictShift:   "恋愛成就より、声を捨てたまま関係に入る危うさが争点になる",
				EndingShape:     "届かないまま消える切なさが残る終わり",
				EndingFlavor:    "喪失",
				StoryTitle:      "声を置いた海辺",
				Hook:            "『人魚姫』を、自分の発言権を代償に近づこうとする恋の話にすると、報われなさの輪郭が濃くなる。",
				Tone:            "透明で痛みのある語り",
			}},
			"view_shift": {{
				VisibleTwist:    "『人魚姫』を、助けられた本人の視点から語り、自分が何も知らないまま誰かを失う残酷さを描く",
				Setting:         "事故後の療養生活",
				Viewpoint:       "助けられた男性の一人称",
				ImmediateChange: "最初に、命の恩人を取り違えていたと後から知る",
				ConflictShift:   "恋愛より、知らなかったことの重さが争点になる",
				EndingShape:     "失ったあとで本当の輪郭だけが残る終わり",
				EndingFlavor:    "喪失",
				StoryTitle:      "知らなかった王子",
				Hook:            "『人魚姫』は、助けられた側から見ると取り返しのつかない誤認の話でもある。",
				Tone:            "遅すぎる気づきのある回想",
			}},
			"value_shift": {{
				VisibleTwist:    "『人魚姫』の献身を、女性が愛のために声を失うことを美化する物語として反転させる",
				Setting:         "自己犠牲を美徳とする恋愛文化",
				Viewpoint:       "声を失う側の一人称",
				ImmediateChange: "冒頭で、愛のために黙ることが褒められていると分かる",
				ConflictShift:   "報われない恋より、沈黙が美徳とされる構造そのものが争点になる",
				EndingShape:     "泡になっても、周囲はきれいな話として消費して終わる",
				EndingFlavor:    "皮肉",
				StoryTitle:      "美しい沈黙",
				Hook:            "『人魚姫』の自己犠牲が、美しい沈黙として消費される話だったら。",
				Tone:            "美しさを疑う現代寓話",
			}},
		},
	},
	"sleepingbeauty": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"招かれなかった魔女", "糸車", "百年の眠り", "森に覆われた城", "目覚め"},
			RoleConstraints:     []string{"呪われる姫", "招かれなかった魔女", "呪いを和らげる存在", "目覚めさせる訪問者"},
			TabooOrRule:         "排除された怒りを軽く見て放置しないこと",
			RewardPunishment:    "排除は長い停止を生み、目覚めには時間と訪問が要る",
			EmotionalAftertaste: "長く止まった時間の静けさが残る",
			RecognitionCues:     []string{"魔女", "糸車", "眠り", "城", "森"},
			RequiredBeats: []StoryBeat{
				storyBeat("curse", "招かれず呪われる", []string{"魔女", "呪い"}, "招かれない"),
				storyBeat("spindle", "糸車で刺す", []string{"糸車", "刺す"}, "針"),
				storyBeat("sleep", "長い眠り", []string{"眠り", "百年"}, "止まる"),
				storyBeat("wake", "城ごと目覚める", []string{"城", "目覚める"}, "森", "起きる"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『眠れる森の美女』を、排除された元職員の報復で組織全体が停止し、長い休眠のあと外からの介入で再起動する話へ置き換える",
				Setting:         "古い研究都市と閉鎖された施設群",
				Viewpoint:       "停止を迎える若い当事者の近接三人称",
				ImmediateChange: "冒頭で、招かれなかった側の怒りが静かに残っている",
				ConflictShift:   "恋愛の奇跡より、長く止まった組織がどう再起動するかが争点になる",
				EndingShape:     "目覚めても止まっていた時間の重さが残る終わり",
				EndingFlavor:    "救い",
				StoryTitle:      "停止した城",
				Hook:            "『眠れる森の美女』を、組織全体が長く止まる休眠事故の話にすると、排除の代償が広く見える。",
				Tone:            "静けさの濃い現代奇譚",
			}},
			"view_shift": {{
				VisibleTwist:    "『眠れる森の美女』を、起こしに来る側の視点から語り、止まった時間の中へ入る怖さを描く",
				Setting:         "封鎖された施設群の内部",
				Viewpoint:       "再起動に入る調査員の一人称",
				ImmediateChange: "最初に、眠る城へ入ること自体が禁忌に近いと明かす",
				ConflictShift:   "姫との出会いより、長く止まった時間へ踏み込む恐れが争点になる",
				EndingShape:     "目覚めた瞬間より、その静けさの長さが残る終わり",
				EndingFlavor:    "救い",
				StoryTitle:      "眠りの森へ入る者",
				Hook:            "『眠れる森の美女』は、起こしに行く側から見ると停止した時間への侵入でもある。",
				Tone:            "静かな探索の語り",
			}},
			"value_shift": {{
				VisibleTwist:    "『眠れる森の美女』の長い眠りを、問題を先送りして凍結する組織文化として反転させる",
				Setting:         "不祥事を凍結して先送りする巨大組織",
				Viewpoint:       "停止の中で待たされる側の一人称",
				ImmediateChange: "冒頭で、眠りは休息ではなく先送りだと分かる",
				ConflictShift:   "呪いより、止めることで責任を先送りする文化が争点になる",
				EndingShape:     "目覚めても、凍結されていた問題だけが山積みで終わる",
				EndingFlavor:    "皮肉",
				StoryTitle:      "百年の先送り",
				Hook:            "『眠れる森の美女』の眠りが、責任を先送りする組織文化そのものだったら。",
				Tone:            "静かで刺すような寓話",
			}},
		},
	},
	"frogprince": {
		Skeleton: StorySkeleton{
			CanonicalMotifs:     []string{"井戸", "金のまり", "蛙との約束", "城まで来る", "王子に戻る"},
			RoleConstraints:     []string{"約束を嫌がる姫", "蛙", "約束を守らせる王", "戻る王子"},
			TabooOrRule:         "嫌でも結んだ約束を踏みにじらないこと",
			RewardPunishment:    "不快な約束を引き受けた先で呪いが解ける",
			EmotionalAftertaste: "嫌悪と受容の距離が妙に残る",
			RecognitionCues:     []string{"井戸", "金のまり", "蛙", "約束", "王子"},
			RequiredBeats: []StoryBeat{
				storyBeat("well", "井戸でまりを落とす", []string{"井戸", "まり"}, "落とす"),
				storyBeat("promise", "蛙と約束する", []string{"蛙", "約束"}, "取り戻す"),
				storyBeat("visit", "城まで来る", []string{"城", "来る"}, "食卓", "泊まる"),
				storyBeat("transform", "王子に戻る", []string{"王子", "戻る"}, "解ける"),
			},
		},
		Twists: map[string][]StoryTwistSeed{
			"role_shift": {{
				VisibleTwist:    "『かえるの王さま』を、軽く交わした約束が後日ほんとうに取り立てられ、嫌悪の先で相手の正体が変わる話へ置き換える",
				Setting:         "古い邸宅と中庭の井戸跡",
				Viewpoint:       "約束を嫌がる若い女性の一人称",
				ImmediateChange: "冒頭で、取り戻したい物のために適当な約束をしてしまう",
				ConflictShift:   "恋愛より、嫌でもした約束をどう引き受けるかが争点になる",
				EndingShape:     "受け入れた瞬間に相手の輪郭が変わる終わり",
				EndingFlavor:    "救い",
				StoryTitle:      "井戸の約束",
				Hook:            "『かえるの王さま』を、軽く交わした約束が後日きっちり取り立てられる話にすると、不快さの意味が変わる。",
				Tone:            "少し癖のある現代童話",
			}},
			"view_shift": {{
				VisibleTwist:    "『かえるの王さま』を、約束を取り立てる側の視点から語り、嫌われながらも約束を守らせる執念を描く",
				Setting:         "城の表玄関と食卓",
				Viewpoint:       "蛙側の一人称",
				ImmediateChange: "最初に、嫌われることを承知で追いかけていると明かす",
				ConflictShift:   "姫の成長より、約束の履行を求める執念が争点になる",
				EndingShape:     "受け入れられた瞬間より、追いかけた日々の疲れが残る終わり",
				EndingFlavor:    "救い",
				StoryTitle:      "蛙が待った扉",
				Hook:            "『かえるの王さま』は、約束を取り立てる側から見ると執念の話でもある。",
				Tone:            "少し執拗で滑稽な語り",
			}},
			"value_shift": {{
				VisibleTwist:    "『かえるの王さま』の約束を、嫌な相手にも誠実であるべきだという圧力として反転させる",
				Setting:         "礼儀と義務が強い上流家庭",
				Viewpoint:       "約束を守らされる側の一人称",
				ImmediateChange: "冒頭で、約束は相手のためより家の体面のためだと分かる",
				ConflictShift:   "呪い解除より、誰のために約束を守るのかが争点になる",
				EndingShape:     "王子に戻っても、同意のあいまいさが残る終わり",
				EndingFlavor:    "皮肉",
				StoryTitle:      "守らされる約束",
				Hook:            "『かえるの王さま』の約束が、礼儀の名で押しつけられる義務だったら。",
				Tone:            "柔らかく苦い現代寓話",
			}},
		},
	},
}
